/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatsSetupCreate } from '../../models/api-heats-setup-create';
import { apiHeatsSetupModel } from '../../models/api-heats-setup-model';

export interface CreateNewHeatsSetupHeatsSetupPost$Params {
      body: apiHeatsSetupCreate
}

export function createNewHeatsSetupHeatsSetupPost(http: HttpClient, rootUrl: string, params: CreateNewHeatsSetupHeatsSetupPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsSetupModel>> {
  const rb = new RequestBuilder(rootUrl, createNewHeatsSetupHeatsSetupPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiHeatsSetupModel>;
    })
  );
}

createNewHeatsSetupHeatsSetupPost.PATH = '/heats_setup/';
