/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatsSetupModel } from '../../models/api-heats-setup-model';

export interface GetHeatsSetupListHeatsSetupGet$Params {
}

export function getHeatsSetupListHeatsSetupGet(http: HttpClient, rootUrl: string, params?: GetHeatsSetupListHeatsSetupGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatsSetupModel>>> {
  const rb = new RequestBuilder(rootUrl, getHeatsSetupListHeatsSetupGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiHeatsSetupModel>>;
    })
  );
}

getHeatsSetupListHeatsSetupGet.PATH = '/heats_setup/';
