/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatsSetupModel } from '../../models/api-heats-setup-model';

export interface GetHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet$Params {
  affiliate_id: number;
}

export function getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet(http: HttpClient, rootUrl: string, params: GetHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatsSetupModel>>> {
  const rb = new RequestBuilder(rootUrl, getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet.PATH, 'get');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiHeatsSetupModel>>;
    })
  );
}

getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet.PATH = '/heats_setup/affiliate/{affiliate_id}';
