/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatsSetupModel } from '../../models/api-heats-setup-model';

export interface GetHeatsSetupByIdHeatsSetupHeatIdGet$Params {
  heat_id: string;
}

export function getHeatsSetupByIdHeatsSetupHeatIdGet(http: HttpClient, rootUrl: string, params: GetHeatsSetupByIdHeatsSetupHeatIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsSetupModel>> {
  const rb = new RequestBuilder(rootUrl, getHeatsSetupByIdHeatsSetupHeatIdGet.PATH, 'get');
  if (params) {
    rb.path('heat_id', params.heat_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiHeatsSetupModel>;
    })
  );
}

getHeatsSetupByIdHeatsSetupHeatIdGet.PATH = '/heats_setup/{heat_id}';
