/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatsSetupModel } from '../../models/api-heats-setup-model';
import { apiHeatsSetupUpdate } from '../../models/api-heats-setup-update';

export interface UpdateExistingHeatsSetupHeatsSetupHeatIdPatch$Params {
  heat_id: string;
      body: apiHeatsSetupUpdate
}

export function updateExistingHeatsSetupHeatsSetupHeatIdPatch(http: HttpClient, rootUrl: string, params: UpdateExistingHeatsSetupHeatsSetupHeatIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsSetupModel>> {
  const rb = new RequestBuilder(rootUrl, updateExistingHeatsSetupHeatsSetupHeatIdPatch.PATH, 'patch');
  if (params) {
    rb.path('heat_id', params.heat_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiHeatsSetupModel>;
    })
  );
}

updateExistingHeatsSetupHeatsSetupHeatIdPatch.PATH = '/heats_setup/{heat_id}';
