/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete$Params {
  affiliate_id: number;
  year: number;
  crossfit_id: number;
  ordinal: number;
}

export function deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete(http: HttpClient, rootUrl: string, params: DeleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete.PATH, 'delete');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.path('crossfit_id', params.crossfit_id, {});
    rb.path('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete.PATH = '/appreciation_score/{affiliate_id}/{year}/{crossfit_id}/{ordinal}';
