/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateAppreciationScoresAppreciationScoreCrossfitIdOrdinalScorePost$Params {
  crossfit_id: number;
  ordinal: number;
  score: number;
}

export function updateAppreciationScoresAppreciationScoreCrossfitIdOrdinalScorePost(http: HttpClient, rootUrl: string, params: UpdateAppreciationScoresAppreciationScoreCrossfitIdOrdinalScorePost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateAppreciationScoresAppreciationScoreCrossfitIdOrdinalScorePost.PATH, 'post');
  if (params) {
    rb.path('crossfit_id', params.crossfit_id, {});
    rb.path('ordinal', params.ordinal, {});
    rb.path('score', params.score, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateAppreciationScoresAppreciationScoreCrossfitIdOrdinalScorePost.PATH = '/appreciation_score/{crossfit_id}/{ordinal}/{score}';
