/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiTeamsModel } from '../../models/api-teams-model';

export interface RenameTeamTeamsRenameAffiliateIdYearTeamNameNewTeamNamePost$Params {
  affiliate_id: number;
  year: number;
  team_name: string;
  new_team_name: string;
}

export function renameTeamTeamsRenameAffiliateIdYearTeamNameNewTeamNamePost(http: HttpClient, rootUrl: string, params: RenameTeamTeamsRenameAffiliateIdYearTeamNameNewTeamNamePost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiTeamsModel>> {
  const rb = new RequestBuilder(rootUrl, renameTeamTeamsRenameAffiliateIdYearTeamNameNewTeamNamePost.PATH, 'post');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.path('team_name', params.team_name, {});
    rb.path('new_team_name', params.new_team_name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiTeamsModel>;
    })
  );
}

renameTeamTeamsRenameAffiliateIdYearTeamNameNewTeamNamePost.PATH = '/teams/rename/{affiliate_id}/{year}/{team_name}/{new_team_name}';
