/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiOAuth2AuthorizeResponse } from '../../models/api-o-auth-2-authorize-response';

export interface OauthAssociateGoogleAuthorizeAuthAssociateGoogleAuthorizeGet$Params {
  scopes?: Array<string>;
}

export function oauthAssociateGoogleAuthorizeAuthAssociateGoogleAuthorizeGet(http: HttpClient, rootUrl: string, params?: OauthAssociateGoogleAuthorizeAuthAssociateGoogleAuthorizeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiOAuth2AuthorizeResponse>> {
  const rb = new RequestBuilder(rootUrl, oauthAssociateGoogleAuthorizeAuthAssociateGoogleAuthorizeGet.PATH, 'get');
  if (params) {
    rb.query('scopes', params.scopes, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiOAuth2AuthorizeResponse>;
    })
  );
}

oauthAssociateGoogleAuthorizeAuthAssociateGoogleAuthorizeGet.PATH = '/auth/associate/google/authorize';
