/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAssignAthletesRequest } from '../../models/api-assign-athletes-request';
import { apiAssignAthletesResponse } from '../../models/api-assign-athletes-response';

export interface AssignAthletesHeatAssignmentsAssignAthletesPost$Params {
      body: apiAssignAthletesRequest
}

export function assignAthletesHeatAssignmentsAssignAthletesPost(http: HttpClient, rootUrl: string, params: AssignAthletesHeatAssignmentsAssignAthletesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAssignAthletesResponse>> {
  const rb = new RequestBuilder(rootUrl, assignAthletesHeatAssignmentsAssignAthletesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiAssignAthletesResponse>;
    })
  );
}

assignAthletesHeatAssignmentsAssignAthletesPost.PATH = '/heat_assignments/assign-athletes';
