/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiRandomAssignmentRequest } from '../../models/api-random-assignment-request';
import { apiRandomAssignmentResponse } from '../../models/api-random-assignment-response';

export interface AssignAthletesAndJudgesHeatAssignmentsAssignRandomPost$Params {
      body: apiRandomAssignmentRequest
}

export function assignAthletesAndJudgesHeatAssignmentsAssignRandomPost(http: HttpClient, rootUrl: string, params: AssignAthletesAndJudgesHeatAssignmentsAssignRandomPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiRandomAssignmentResponse>> {
  const rb = new RequestBuilder(rootUrl, assignAthletesAndJudgesHeatAssignmentsAssignRandomPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiRandomAssignmentResponse>;
    })
  );
}

assignAthletesAndJudgesHeatAssignmentsAssignRandomPost.PATH = '/heat_assignments/assign-random';
