/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatAttendanceModel } from '../../models/api-heat-attendance-model';

export interface GetHeatAttendanceHeatAssignmentsHeatAttendanceGet$Params {
  affiliate_id: number;
  year: number;
  ordinal: number;
}

export function getHeatAttendanceHeatAssignmentsHeatAttendanceGet(http: HttpClient, rootUrl: string, params: GetHeatAttendanceHeatAssignmentsHeatAttendanceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatAttendanceModel>>> {
  const rb = new RequestBuilder(rootUrl, getHeatAttendanceHeatAssignmentsHeatAttendanceGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
    rb.query('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiHeatAttendanceModel>>;
    })
  );
}

getHeatAttendanceHeatAssignmentsHeatAttendanceGet.PATH = '/heat_assignments/heat-attendance';
