/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatAssignmentModel } from '../../models/api-heat-assignment-model';

export interface GetMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet$Params {
  year: number;
  ordinal: number;
}

export function getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet(http: HttpClient, rootUrl: string, params: GetMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatAssignmentModel>> {
  const rb = new RequestBuilder(rootUrl, getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
    rb.query('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiHeatAssignmentModel>;
    })
  );
}

getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet.PATH = '/heat_assignments/me-athlete';
