/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatAssignmentModel } from '../../models/api-heat-assignment-model';
import { apiHeatAssignmentUpdate } from '../../models/api-heat-assignment-update';

export interface UpdateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch$Params {
  assignment_id: string;
      body: apiHeatAssignmentUpdate
}

export function updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch(http: HttpClient, rootUrl: string, params: UpdateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatAssignmentModel>> {
  const rb = new RequestBuilder(rootUrl, updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch.PATH, 'patch');
  if (params) {
    rb.path('assignment_id', params.assignment_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiHeatAssignmentModel>;
    })
  );
}

updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch.PATH = '/heat_assignments/{assignment_id}';
