[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all,standard]>=0.115.11",
    "firebase-admin>=6.7.0",
    "httpx>=0.28.1",
    "sqlalchemy>=2.0.39",
]
