HEATS_SETUP = [
    {
        "affiliate_id": 31316,
        "short_name": "Fri AM",
        "start_time": "08:00",
        "end_time": "09:00",
        "interval": 30,
        "max_athletes": 10,
    },
    {
        "affiliate_id": 31316,
        "short_name": "Fri PM",
        "start_time": "17:30",
        "end_time": "20:00",
        "interval": 30,
        "max_athletes": 10,
    },
    {
        "affiliate_id": 31316,
        "short_name": "Sat AM",
        "start_time": "06:00",
        "end_time": "10:00",
        "interval": 30,
        "max_athletes": 10,
    },
    {
        "affiliate_id": 31316,
        "short_name": "Sat PM",
        "start_time": "17:30",
        "end_time": "20:00",
        "interval": 30,
        "max_athletes": 10,
    },
    {
        "affiliate_id": 31316,
        "short_name": "Sun AM",
        "start_time": "06:00",
        "end_time": "10:00",
        "interval": 30,
        "max_athletes": 10,
    },
    {
        "affiliate_id": 31316,
        "short_name": "Mon AM",
        "start_time": "08:00",
        "end_time": "10:00",
        "interval": 30,
        "max_athletes": 10,
    },
    {
        "affiliate_id": 31316,
        "short_name": "Mon PM",
        "start_time": "18:00",
        "end_time": "19:00",
        "interval": 30,
        "max_athletes": 10,
    },
]
