/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAppreciationStatusModel } from '../../models/api-appreciation-status-model';

export interface GetOpenAppreciationStatusAppreciationOpenGet$Params {
  year: number;
}

export function getOpenAppreciationStatusAppreciationOpenGet(http: HttpClient, rootUrl: string, params: GetOpenAppreciationStatusAppreciationOpenGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAppreciationStatusModel>>> {
  const rb = new RequestBuilder(rootUrl, getOpenAppreciationStatusAppreciationOpenGet.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAppreciationStatusModel>>;
    })
  );
}

getOpenAppreciationStatusAppreciationOpenGet.PATH = '/appreciation_open/';
