/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAthletePrefsModel } from '../../models/api-athlete-prefs-model';

export interface GetMyPrefsAthletePrefsMeGet$Params {
}

export function getMyPrefsAthletePrefsMeGet(http: HttpClient, rootUrl: string, params?: GetMyPrefsAthletePrefsMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAthletePrefsModel>>> {
  const rb = new RequestBuilder(rootUrl, getMyPrefsAthletePrefsMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAthletePrefsModel>>;
    })
  );
}

getMyPrefsAthletePrefsMeGet.PATH = '/athlete-prefs/me';
