/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAffiliateAthlete {
  affiliate_id: number;
  affiliate_name: string;
  crossfit_id: number;
  name: string;
}
