/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthletePrefsModel {
  created_at: string;
  mf_age_category: string;
  name: string;
  preference: string;
  preference_nbr: number;
  rx_pref: string;
  team_name: string;
  updated_at: string;
}
