/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiEventsModel {
  event: string;
  ordinal: number;
  start_date?: (string | null);
  year: number;
}
