/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiIndividualSideScoreModel {
  affiliate_id: number;
  crossfit_id: number;
  ordinal: number;
  score: number;
  score_type: 'appreciation' | 'rookie';
  year: number;
}
