/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiHeatsUpdate {
  max_athletes?: (number | null);
  short_name?: (string | null);
  start_time?: (string | null);
}
