/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAffiliateConfigModel {
  affiliate_id: number;
  appreciation_score?: number;
  attendance_score?: number;
  judge_score?: number;
  participation_score?: number;
  rookie_score?: number;
  side_challenge_score?: number;
  spirit_score?: number;
  top3_score?: number;
  use_appreciation?: boolean;
  use_scheduling?: boolean;
  year: number;
}
