/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiPreferredAthleteModel {
  crossfit_id: number;
  id: string;
  name: string;
  start_time: string;
}
