/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiJudgesUpdate {
  affiliate_id?: (number | null);
  crossfit_id?: (number | null);
  name?: (string | null);
  preferred?: (boolean | null);
}
