/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAppreciationCountsModel {
  affiliate_id: number;
  count: number;
  ordinal: number;
  year: number;
}
