/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAppreciationModelInput {
  non_team_vote_athlete_id: string;
  non_team_vote_text: (string | null);
  team_vote_athlete_id: string;
  team_vote_text: (string | null);
}
