/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiFirebaseCustomClaims {
  admin?: boolean;
  affiliate_id: (number | null);
  affiliate_name: (string | null);
  crossfit_id: (number | null);
}
