/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiTeamScoreModel {
  affiliate_id: number;
  appreciation_score: number;
  attendance_score: number;
  judge_score: number;
  ordinal?: (number | null);
  participation_score: number;
  side_challenge_score: number;
  spirit_score: number;
  team_name: string;
  top3_score: number;
  total_individual_score: number;
  total_team_score: number;
  year: number;
}
