/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiHeatsSetupModel {
  affiliate_id: number;
  end_time: string;
  id: string;
  interval: number;
  max_athletes?: (number | null);
  short_name: string;
  start_time: string;
}
