/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthleteSummaryCounts {
  affiliate_id: number;
  affiliate_name: string;
  athlete_count: number;
  year: number;
}
