/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthleteNotSignedUp {
  age: number;
  crossfit_id: number;
  division_id: number;
  first_name: string;
  gender: string;
  last_name: string;
  name: string;
  team_name: string;
}
