/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAutoTeamAssignmentInput {
  affiliate_id: number;
  assign_from_team_name: string;
  assign_to_team_names: Array<string>;
  year: number;
}
