/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiUserRead {
  affiliate: string;
  affiliate_id: number;
  athlete_id: number;
  email: string;
  id: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
  name: string;
}
