/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiPreferredAthletesInitResponse {
  inserted: number;
  processed: number;
  updated: number;
}
