/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiHeatAttendanceModel {
  athlete_crossfit_id: number;
  athlete_name: string;
  email: (string | null);
  start_time: string;
}
