/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiTeamsModel {
  affiliate_id: number;
  instagram: string;
  logo_url: string;
  team_name: string;
  year: number;
}
