/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiJudgeAvailabilityCreate {
  available?: boolean;
  judge_id: string;
  time_slot: string;
}
