/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiCreateUser {
  affiliate_id: number;
  affiliate_name: string;
  crossfit_id: number;
  display_name: string;
  email: string;
  password: string;
}
