/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiJudgesModel {
  affiliate_id: number;
  crossfit_id: number;
  id: string;
  name: string;
  preferred: boolean;
}
