/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthletePrefsOutputModel {
  competitor_id: number;
  name: string;
  preference: string;
  preference_nbr: number;
}
