/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiScoreModel {
  affiliate_id: number;
  affiliate_rank?: (number | null);
  affiliate_scaled: 'RX' | 'Scaled';
  age_category: 'Open' | 'Masters' | 'Masters 55+';
  appreciation_score: number;
  attendance_score: number;
  gender: 'M' | 'F';
  judge_score: number;
  name: string;
  ordinal: number;
  participation_score: number;
  score_display?: (string | null);
  side_challenge_score: number;
  spirit_score: number;
  team_name?: (string | null);
  tiebeak_ms?: (string | null);
  top3_score: number;
  total_score: number;
  year: number;
}
