/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiHeatAssignmentModel {
  athlete_crossfit_id: (number | null);
  athlete_name: (string | null);
  heat_id: string;
  id: string;
  is_locked: boolean;
  is_published: boolean;
  judge_crossfit_id: (number | null);
  judge_name: (string | null);
  preference_nbr: (number | null);
}
