/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAthletePrefsModel {
  athlete_id: string;
  preference: string;
  preference_nbr: number;
}
