/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiPreferredAthleteUpdate {
  affiliate_id?: (number | null);
  crossfit_id?: (number | null);
  name?: (string | null);
  start_time?: (string | null);
}
