/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiDeleteAssignmentsByCriteriaResponse {
  deleted_count: number;
  heats_found: number;
  message: string;
}
