/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiHeatsModel {
  affiliate_id: number;
  id: string;
  max_athletes?: (number | null);
  ordinal: number;
  short_name: string;
  start_time: string;
  year: number;
}
