/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAffiliateConfigModel {
  affiliate_id: number;
  attendance_score?: number;
  default_appreciation_score?: number;
  default_side_score?: number;
  judge_score?: number;
  masters_age_cutoff?: number;
  open_age_cutoff?: number;
  participation_score?: number;
  top3_score?: number;
  year: number;
}
