/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAppreciationModel {
  affiliate_id: number;
  crossfit_id: number;
  non_team_vote_crossfit_id: number;
  non_team_vote_text: (string | null);
  ordinal: number;
  team_vote_crossfit_id: number;
  team_vote_text: (string | null);
  year: number;
}
