/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiCreateHomeBlogModel {
  action_link?: (string | null);
  action_text?: (string | null);
  content: string;
  image_link?: (string | null);
  subtitle?: (string | null);
  title: string;
}
