/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiAssignAthletesResponse {
  athletes_assigned: number;
  heats_processed: number;
  skipped_athletes: Array<{
[key: string]: (string | number);
}>;
}
