/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface apiPreferredAthleteCreate {
  affiliate_id: number;
  crossfit_id: number;
  name: string;
  start_time: string;
}
