/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgesCreate } from '../../models/api-judges-create';
import { apiJudgesModel } from '../../models/api-judges-model';

export interface CreateNewJudgeJudgesPost$Params {
      body: apiJudgesCreate
}

export function createNewJudgeJudgesPost(http: HttpClient, rootUrl: string, params: CreateNewJudgeJudgesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgesModel>> {
  const rb = new RequestBuilder(rootUrl, createNewJudgeJudgesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiJudgesModel>;
    })
  );
}

createNewJudgeJudgesPost.PATH = '/judges/';
