/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgesModel } from '../../models/api-judges-model';

export interface GetJudgeByIdJudgesJudgeIdGet$Params {
  judge_id: string;
}

export function getJudgeByIdJudgesJudgeIdGet(http: HttpClient, rootUrl: string, params: GetJudgeByIdJudgesJudgeIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgesModel>> {
  const rb = new RequestBuilder(rootUrl, getJudgeByIdJudgesJudgeIdGet.PATH, 'get');
  if (params) {
    rb.path('judge_id', params.judge_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiJudgesModel>;
    })
  );
}

getJudgeByIdJudgesJudgeIdGet.PATH = '/judges/{judge_id}';
