/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgesModel } from '../../models/api-judges-model';

export interface GetJudgesListJudgesAllGet$Params {
  affiliate_id: number;
}

export function getJudgesListJudgesAllGet(http: HttpClient, rootUrl: string, params: GetJudgesListJudgesAllGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiJudgesModel>>> {
  const rb = new RequestBuilder(rootUrl, getJudgesListJudgesAllGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiJudgesModel>>;
    })
  );
}

getJudgesListJudgesAllGet.PATH = '/judges/all';
