/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgesModel } from '../../models/api-judges-model';

export interface GetJudgesListJudgesGet$Params {
}

export function getJudgesListJudgesGet(http: HttpClient, rootUrl: string, params?: GetJudgesListJudgesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiJudgesModel>>> {
  const rb = new RequestBuilder(rootUrl, getJudgesListJudgesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiJudgesModel>>;
    })
  );
}

getJudgesListJudgesGet.PATH = '/judges/';
