/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgesModel } from '../../models/api-judges-model';

export interface GetJudgeByIdCrossfitJudgesAffiliateIdCrossfitIdCrossfitIdGet$Params {
  affiliate_id: number;
  crossfit_id: number;
}

export function getJudgeByIdCrossfitJudgesAffiliateIdCrossfitIdCrossfitIdGet(http: HttpClient, rootUrl: string, params: GetJudgeByIdCrossfitJudgesAffiliateIdCrossfitIdCrossfitIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgesModel>> {
  const rb = new RequestBuilder(rootUrl, getJudgeByIdCrossfitJudgesAffiliateIdCrossfitIdCrossfitIdGet.PATH, 'get');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('crossfit_id', params.crossfit_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiJudgesModel>;
    })
  );
}

getJudgeByIdCrossfitJudgesAffiliateIdCrossfitIdCrossfitIdGet.PATH = '/judges/{affiliate_id}/crossfit_id/{crossfit_id}';
