/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface InitJudgesJudgesInitializeAffiliateIdPost$Params {
  affiliate_id: number;
}

export function initJudgesJudgesInitializeAffiliateIdPost(http: HttpClient, rootUrl: string, params: InitJudgesJudgesInitializeAffiliateIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
  const rb = new RequestBuilder(rootUrl, initJudgesJudgesInitializeAffiliateIdPost.PATH, 'post');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: string;
      }>;
    })
  );
}

initJudgesJudgesInitializeAffiliateIdPost.PATH = '/judges/initialize/{affiliate_id}';
