/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgesModel } from '../../models/api-judges-model';
import { apiJudgesUpdate } from '../../models/api-judges-update';

export interface UpdateExistingJudgeJudgesJudgeIdPatch$Params {
  judge_id: string;
      body: apiJudgesUpdate
}

export function updateExistingJudgeJudgesJudgeIdPatch(http: HttpClient, rootUrl: string, params: UpdateExistingJudgeJudgesJudgeIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgesModel>> {
  const rb = new RequestBuilder(rootUrl, updateExistingJudgeJudgesJudgeIdPatch.PATH, 'patch');
  if (params) {
    rb.path('judge_id', params.judge_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiJudgesModel>;
    })
  );
}

updateExistingJudgeJudgesJudgeIdPatch.PATH = '/judges/{judge_id}';
