/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAppreciationCountsModel } from '../../models/api-appreciation-counts-model';

export interface GetAppreciationCountsAppreciationCountsGet$Params {
  affiliate_id: number;
  year: number;
  ordinal?: (number | null);
}

export function getAppreciationCountsAppreciationCountsGet(http: HttpClient, rootUrl: string, params: GetAppreciationCountsAppreciationCountsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAppreciationCountsModel>>> {
  const rb = new RequestBuilder(rootUrl, getAppreciationCountsAppreciationCountsGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
    rb.query('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAppreciationCountsModel>>;
    })
  );
}

getAppreciationCountsAppreciationCountsGet.PATH = '/appreciation/counts';
