/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAppreciationResultNotes } from '../../models/api-appreciation-result-notes';

export interface GetMyAppreciationTextAppreciationMyAppreciationTextGet$Params {
  year: number;
}

export function getMyAppreciationTextAppreciationMyAppreciationTextGet(http: HttpClient, rootUrl: string, params: GetMyAppreciationTextAppreciationMyAppreciationTextGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAppreciationResultNotes>>> {
  const rb = new RequestBuilder(rootUrl, getMyAppreciationTextAppreciationMyAppreciationTextGet.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAppreciationResultNotes>>;
    })
  );
}

getMyAppreciationTextAppreciationMyAppreciationTextGet.PATH = '/appreciation/my-appreciation-text';
