/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAppreciationModelOutput } from '../../models/api-appreciation-model-output';

export interface GetAppreciationAppreciationAffiliateIdYearOrdinalGet$Params {
  affiliate_id: number;
  year: number;
  ordinal: number;
}

export function getAppreciationAppreciationAffiliateIdYearOrdinalGet(http: HttpClient, rootUrl: string, params: GetAppreciationAppreciationAffiliateIdYearOrdinalGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAppreciationModelOutput>>> {
  const rb = new RequestBuilder(rootUrl, getAppreciationAppreciationAffiliateIdYearOrdinalGet.PATH, 'get');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.path('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAppreciationModelOutput>>;
    })
  );
}

getAppreciationAppreciationAffiliateIdYearOrdinalGet.PATH = '/appreciation/{affiliate_id}/{year}/{ordinal}';
