/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { apiAffiliateAthlete } from './models/api-affiliate-athlete';
export type { apiAppreciationModelInput } from './models/api-appreciation-model-input';
export type { apiAppreciationModelOutput } from './models/api-appreciation-model-output';
export type { apiAppreciationScoreModel } from './models/api-appreciation-score-model';
export type { apiAthleteDetail } from './models/api-athlete-detail';
export type { apiAthletePrefsModel } from './models/api-athlete-prefs-model';
export type { apiAthletePrefsOutputModel } from './models/api-athlete-prefs-output-model';
export type { apiAttendanceModel } from './models/api-attendance-model';
export type { apiCreateUser } from './models/api-create-user';
export type { apiEventsModel } from './models/api-events-model';
export type { apiFirebaseCustomClaims } from './models/api-firebase-custom-claims';
export type { apiFirebaseUserRecord } from './models/api-firebase-user-record';
export type { apiHttpValidationError } from './models/api-http-validation-error';
export type { apiIndividualScoreModel } from './models/api-individual-score-model';
export type { apiLeaderboardScoreModel } from './models/api-leaderboard-score-model';
export type { apiSideScoreModel } from './models/api-side-score-model';
export type { apiTeamScoreModel } from './models/api-team-score-model';
export type { apiTeamsModel } from './models/api-teams-model';
export type { apiUserScoreModel } from './models/api-user-score-model';
export type { apiValidationError } from './models/api-validation-error';
