/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { apiAuthService } from './services/api-auth.service';
export { apiAthleteService } from './services/api-athlete.service';
export { apiScoreService } from './services/api-score.service';
export { apiAttendanceService } from './services/api-attendance.service';
export { apiAppreciationService } from './services/api-appreciation.service';
export { apiSidescoreService } from './services/api-sidescore.service';
export { apiTeamsService } from './services/api-teams.service';
export { apiAthletePrefsService } from './services/api-athlete-prefs.service';
