/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { apiCfeventsService } from './services/api-cfevents.service';
export { apiFireauthService } from './services/api-fireauth.service';
export { apiAthleteService } from './services/api-athlete.service';
export { apiScoreService } from './services/api-score.service';
export { apiAttendanceService } from './services/api-attendance.service';
export { apiAppreciationScoreService } from './services/api-appreciation-score.service';
export { apiAppreciationService } from './services/api-appreciation.service';
export { apiAppreciationStatusService } from './services/api-appreciation-status.service';
export { apiSidescoreService } from './services/api-sidescore.service';
export { apiTeamsService } from './services/api-teams.service';
export { apiAthletePrefsService } from './services/api-athlete-prefs.service';
