/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { apiCfeventsService } from './services/api-cfevents.service';
export { apiCfgamesService } from './services/api-cfgames.service';
export { apiFireauthService } from './services/api-fireauth.service';
export { apiAthleteService } from './services/api-athlete.service';
export { apiScoreService } from './services/api-score.service';
export { apiAttendanceService } from './services/api-attendance.service';
export { apiIndividualSideScoreService } from './services/api-individual-side-score.service';
export { apiAppreciationService } from './services/api-appreciation.service';
export { apiAppreciationStatusService } from './services/api-appreciation-status.service';
export { apiSidescoreService } from './services/api-sidescore.service';
export { apiAthletePrefsService } from './services/api-athlete-prefs.service';
export { apiJudgesService } from './services/api-judges.service';
export { apiJudgeAvailabilityService } from './services/api-judge-availability.service';
export { apiPreferredAthletesService } from './services/api-preferred-athletes.service';
export { apiHeatsService } from './services/api-heats.service';
export { apiHeatsSetupService } from './services/api-heats-setup.service';
export { apiHeatAssignmentsService } from './services/api-heat-assignments.service';
export { apiHomeBlogService } from './services/api-home-blog.service';
export { apiAffiliateConfigService } from './services/api-affiliate-config.service';
