/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { applyAppreciationAppreciationScoreApplyPost } from '../fn/appreciation-score/apply-appreciation-appreciation-score-apply-post';
import { ApplyAppreciationAppreciationScoreApplyPost$Params } from '../fn/appreciation-score/apply-appreciation-appreciation-score-apply-post';
import { apiAppreciationScoreModel } from '../models/api-appreciation-score-model';
import { deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete } from '../fn/appreciation-score/delete-appreciation-scores-appreciation-score-affiliate-id-year-crossfit-id-ordinal-delete';
import { DeleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete$Params } from '../fn/appreciation-score/delete-appreciation-scores-appreciation-score-affiliate-id-year-crossfit-id-ordinal-delete';
import { getAppreciationScoresAppreciationScoreAffiliateIdYearGet } from '../fn/appreciation-score/get-appreciation-scores-appreciation-score-affiliate-id-year-get';
import { GetAppreciationScoresAppreciationScoreAffiliateIdYearGet$Params } from '../fn/appreciation-score/get-appreciation-scores-appreciation-score-affiliate-id-year-get';
import { updateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost } from '../fn/appreciation-score/update-appreciation-scores-appreciation-score-affiliate-id-year-crossfit-id-ordinal-score-post';
import { UpdateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost$Params } from '../fn/appreciation-score/update-appreciation-scores-appreciation-score-affiliate-id-year-crossfit-id-ordinal-score-post';

@Injectable({ providedIn: 'root' })
export class apiAppreciationScoreService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAppreciationScoresAppreciationScoreAffiliateIdYearGet()` */
  static readonly GetAppreciationScoresAppreciationScoreAffiliateIdYearGetPath = '/appreciation_score/{affiliate_id}/{year}/';

  /**
   * Get Appreciation Scores.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAppreciationScoresAppreciationScoreAffiliateIdYearGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAppreciationScoresAppreciationScoreAffiliateIdYearGet$Response(params: GetAppreciationScoresAppreciationScoreAffiliateIdYearGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAppreciationScoreModel>>> {
    return getAppreciationScoresAppreciationScoreAffiliateIdYearGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Appreciation Scores.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAppreciationScoresAppreciationScoreAffiliateIdYearGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAppreciationScoresAppreciationScoreAffiliateIdYearGet(params: GetAppreciationScoresAppreciationScoreAffiliateIdYearGet$Params, context?: HttpContext): Observable<Array<apiAppreciationScoreModel>> {
    return this.getAppreciationScoresAppreciationScoreAffiliateIdYearGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiAppreciationScoreModel>>): Array<apiAppreciationScoreModel> => r.body)
    );
  }

  /** Path part for operation `updateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost()` */
  static readonly UpdateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePostPath = '/appreciation_score/{affiliate_id}/{year}/{crossfit_id}/{ordinal}/{score}';

  /**
   * Update Appreciation Scores.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost$Response(params: UpdateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return updateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Appreciation Scores.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost(params: UpdateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost$Params, context?: HttpContext): Observable<any> {
    return this.updateAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalScorePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

  /** Path part for operation `deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete()` */
  static readonly DeleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDeletePath = '/appreciation_score/{affiliate_id}/{year}/{crossfit_id}/{ordinal}';

  /**
   * Delete Appreciation Scores.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete$Response(params: DeleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Appreciation Scores.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete(params: DeleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete$Params, context?: HttpContext): Observable<void> {
    return this.deleteAppreciationScoresAppreciationScoreAffiliateIdYearCrossfitIdOrdinalDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `applyAppreciationAppreciationScoreApplyPost()` */
  static readonly ApplyAppreciationAppreciationScoreApplyPostPath = '/appreciation_score/apply';

  /**
   * Apply Appreciation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `applyAppreciationAppreciationScoreApplyPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  applyAppreciationAppreciationScoreApplyPost$Response(params: ApplyAppreciationAppreciationScoreApplyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return applyAppreciationAppreciationScoreApplyPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Apply Appreciation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `applyAppreciationAppreciationScoreApplyPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  applyAppreciationAppreciationScoreApplyPost(params: ApplyAppreciationAppreciationScoreApplyPost$Params, context?: HttpContext): Observable<any> {
    return this.applyAppreciationAppreciationScoreApplyPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
