/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { applyAttendanceAttendanceApplyPost } from '../fn/attendance/apply-attendance-attendance-apply-post';
import { ApplyAttendanceAttendanceApplyPost$Params } from '../fn/attendance/apply-attendance-attendance-apply-post';
import { apiAttendanceModel } from '../models/api-attendance-model';
import { getAttendanceAttendanceGet } from '../fn/attendance/get-attendance-attendance-get';
import { GetAttendanceAttendanceGet$Params } from '../fn/attendance/get-attendance-attendance-get';
import { updateAttendanceAttendanceUpdatePost } from '../fn/attendance/update-attendance-attendance-update-post';
import { UpdateAttendanceAttendanceUpdatePost$Params } from '../fn/attendance/update-attendance-attendance-update-post';

@Injectable({ providedIn: 'root' })
export class apiAttendanceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAttendanceAttendanceGet()` */
  static readonly GetAttendanceAttendanceGetPath = '/attendance/';

  /**
   * Get Attendance.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAttendanceAttendanceGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAttendanceAttendanceGet$Response(params: GetAttendanceAttendanceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAttendanceModel>>> {
    return getAttendanceAttendanceGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Attendance.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAttendanceAttendanceGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAttendanceAttendanceGet(params: GetAttendanceAttendanceGet$Params, context?: HttpContext): Observable<Array<apiAttendanceModel>> {
    return this.getAttendanceAttendanceGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiAttendanceModel>>): Array<apiAttendanceModel> => r.body)
    );
  }

  /** Path part for operation `updateAttendanceAttendanceUpdatePost()` */
  static readonly UpdateAttendanceAttendanceUpdatePostPath = '/attendance/update';

  /**
   * Update Attendance.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAttendanceAttendanceUpdatePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAttendanceAttendanceUpdatePost$Response(params: UpdateAttendanceAttendanceUpdatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAttendanceModel>> {
    return updateAttendanceAttendanceUpdatePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Attendance.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAttendanceAttendanceUpdatePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAttendanceAttendanceUpdatePost(params: UpdateAttendanceAttendanceUpdatePost$Params, context?: HttpContext): Observable<apiAttendanceModel> {
    return this.updateAttendanceAttendanceUpdatePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiAttendanceModel>): apiAttendanceModel => r.body)
    );
  }

  /** Path part for operation `applyAttendanceAttendanceApplyPost()` */
  static readonly ApplyAttendanceAttendanceApplyPostPath = '/attendance/apply';

  /**
   * Apply Attendance.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `applyAttendanceAttendanceApplyPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  applyAttendanceAttendanceApplyPost$Response(params: ApplyAttendanceAttendanceApplyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return applyAttendanceAttendanceApplyPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Apply Attendance.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `applyAttendanceAttendanceApplyPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  applyAttendanceAttendanceApplyPost(params: ApplyAttendanceAttendanceApplyPost$Params, context?: HttpContext): Observable<any> {
    return this.applyAttendanceAttendanceApplyPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
