/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createNewHeatHeatsPost } from '../fn/heats/create-new-heat-heats-post';
import { CreateNewHeatHeatsPost$Params } from '../fn/heats/create-new-heat-heats-post';
import { deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete } from '../fn/heats/delete-existing-heat-heats-year-affiliate-id-ordinal-start-time-delete';
import { DeleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete$Params } from '../fn/heats/delete-existing-heat-heats-year-affiliate-id-ordinal-start-time-delete';
import { deleteHeatsBulkHeatsBulkDelete } from '../fn/heats/delete-heats-bulk-heats-bulk-delete';
import { DeleteHeatsBulkHeatsBulkDelete$Params } from '../fn/heats/delete-heats-bulk-heats-bulk-delete';
import { generateHeatsFromSetupHeatsGeneratePost } from '../fn/heats/generate-heats-from-setup-heats-generate-post';
import { GenerateHeatsFromSetupHeatsGeneratePost$Params } from '../fn/heats/generate-heats-from-setup-heats-generate-post';
import { getHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet } from '../fn/heats/get-heat-by-id-heats-year-affiliate-id-ordinal-start-time-get';
import { GetHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet$Params } from '../fn/heats/get-heat-by-id-heats-year-affiliate-id-ordinal-start-time-get';
import { getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet } from '../fn/heats/get-heats-by-filter-heats-filter-year-affiliate-id-ordinal-get';
import { GetHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet$Params } from '../fn/heats/get-heats-by-filter-heats-filter-year-affiliate-id-ordinal-get';
import { apiHeatsModel } from '../models/api-heats-model';
import { toggleLockedHeatsToggleLockedPost } from '../fn/heats/toggle-locked-heats-toggle-locked-post';
import { ToggleLockedHeatsToggleLockedPost$Params } from '../fn/heats/toggle-locked-heats-toggle-locked-post';
import { togglePublishedHeatsTogglePublishedPost } from '../fn/heats/toggle-published-heats-toggle-published-post';
import { TogglePublishedHeatsTogglePublishedPost$Params } from '../fn/heats/toggle-published-heats-toggle-published-post';
import { apiToggleResponse } from '../models/api-toggle-response';
import { updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch } from '../fn/heats/update-existing-heat-heats-year-affiliate-id-ordinal-start-time-patch';
import { UpdateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch$Params } from '../fn/heats/update-existing-heat-heats-year-affiliate-id-ordinal-start-time-patch';

@Injectable({ providedIn: 'root' })
export class apiHeatsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet()` */
  static readonly GetHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGetPath = '/heats/filter/{year}/{affiliate_id}/{ordinal}';

  /**
   * Get Heats By Filter.
   *
   * Get all heats for a specific affiliate, year, and ordinal.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet$Response(params: GetHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatsModel>>> {
    return getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Heats By Filter.
   *
   * Get all heats for a specific affiliate, year, and ordinal.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet(params: GetHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet$Params, context?: HttpContext): Observable<Array<apiHeatsModel>> {
    return this.getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiHeatsModel>>): Array<apiHeatsModel> => r.body)
    );
  }

  /** Path part for operation `getHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet()` */
  static readonly GetHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGetPath = '/heats/{year}/{affiliate_id}/{ordinal}/{start_time}';

  /**
   * Get Heat By Id.
   *
   * Get a specific heat by its composite primary key.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet$Response(params: GetHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsModel>> {
    return getHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Heat By Id.
   *
   * Get a specific heat by its composite primary key.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet(params: GetHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet$Params, context?: HttpContext): Observable<apiHeatsModel> {
    return this.getHeatByIdHeatsYearAffiliateIdOrdinalStartTimeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatsModel>): apiHeatsModel => r.body)
    );
  }

  /** Path part for operation `deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete()` */
  static readonly DeleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDeletePath = '/heats/{year}/{affiliate_id}/{ordinal}/{start_time}';

  /**
   * Delete Existing Heat.
   *
   * Delete a heat.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete$Response(params: DeleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Existing Heat.
   *
   * Delete a heat.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete(params: DeleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete$Params, context?: HttpContext): Observable<void> {
    return this.deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch()` */
  static readonly UpdateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatchPath = '/heats/{year}/{affiliate_id}/{ordinal}/{start_time}';

  /**
   * Update Existing Heat.
   *
   * Update an existing heat.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch$Response(params: UpdateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsModel>> {
    return updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Existing Heat.
   *
   * Update an existing heat.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch(params: UpdateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch$Params, context?: HttpContext): Observable<apiHeatsModel> {
    return this.updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatsModel>): apiHeatsModel => r.body)
    );
  }

  /** Path part for operation `createNewHeatHeatsPost()` */
  static readonly CreateNewHeatHeatsPostPath = '/heats/';

  /**
   * Create New Heat.
   *
   * Create a new heat.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createNewHeatHeatsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewHeatHeatsPost$Response(params: CreateNewHeatHeatsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsModel>> {
    return createNewHeatHeatsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create New Heat.
   *
   * Create a new heat.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createNewHeatHeatsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewHeatHeatsPost(params: CreateNewHeatHeatsPost$Params, context?: HttpContext): Observable<apiHeatsModel> {
    return this.createNewHeatHeatsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatsModel>): apiHeatsModel => r.body)
    );
  }

  /** Path part for operation `generateHeatsFromSetupHeatsGeneratePost()` */
  static readonly GenerateHeatsFromSetupHeatsGeneratePostPath = '/heats/generate';

  /**
   * Generate Heats From Setup.
   *
   * Generate heats based on the affiliate's predefined setup for an event.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateHeatsFromSetupHeatsGeneratePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateHeatsFromSetupHeatsGeneratePost$Response(params: GenerateHeatsFromSetupHeatsGeneratePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatsModel>>> {
    return generateHeatsFromSetupHeatsGeneratePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Generate Heats From Setup.
   *
   * Generate heats based on the affiliate's predefined setup for an event.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateHeatsFromSetupHeatsGeneratePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateHeatsFromSetupHeatsGeneratePost(params: GenerateHeatsFromSetupHeatsGeneratePost$Params, context?: HttpContext): Observable<Array<apiHeatsModel>> {
    return this.generateHeatsFromSetupHeatsGeneratePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiHeatsModel>>): Array<apiHeatsModel> => r.body)
    );
  }

  /** Path part for operation `deleteHeatsBulkHeatsBulkDelete()` */
  static readonly DeleteHeatsBulkHeatsBulkDeletePath = '/heats/bulk';

  /**
   * Delete Heats Bulk.
   *
   * Delete all heats for a specific affiliate, year, and ordinal.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteHeatsBulkHeatsBulkDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteHeatsBulkHeatsBulkDelete$Response(params: DeleteHeatsBulkHeatsBulkDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return deleteHeatsBulkHeatsBulkDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Heats Bulk.
   *
   * Delete all heats for a specific affiliate, year, and ordinal.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteHeatsBulkHeatsBulkDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteHeatsBulkHeatsBulkDelete(params: DeleteHeatsBulkHeatsBulkDelete$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.deleteHeatsBulkHeatsBulkDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `togglePublishedHeatsTogglePublishedPost()` */
  static readonly TogglePublishedHeatsTogglePublishedPostPath = '/heats/toggle-published';

  /**
   * Toggle Published.
   *
   * Toggle the published status of all heat assignments for a specific heat.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `togglePublishedHeatsTogglePublishedPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  togglePublishedHeatsTogglePublishedPost$Response(params: TogglePublishedHeatsTogglePublishedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiToggleResponse>> {
    return togglePublishedHeatsTogglePublishedPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle Published.
   *
   * Toggle the published status of all heat assignments for a specific heat.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `togglePublishedHeatsTogglePublishedPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  togglePublishedHeatsTogglePublishedPost(params: TogglePublishedHeatsTogglePublishedPost$Params, context?: HttpContext): Observable<apiToggleResponse> {
    return this.togglePublishedHeatsTogglePublishedPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiToggleResponse>): apiToggleResponse => r.body)
    );
  }

  /** Path part for operation `toggleLockedHeatsToggleLockedPost()` */
  static readonly ToggleLockedHeatsToggleLockedPostPath = '/heats/toggle-locked';

  /**
   * Toggle Locked.
   *
   * Toggle the locked status of all heat assignments for a specific heat.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `toggleLockedHeatsToggleLockedPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  toggleLockedHeatsToggleLockedPost$Response(params: ToggleLockedHeatsToggleLockedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiToggleResponse>> {
    return toggleLockedHeatsToggleLockedPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle Locked.
   *
   * Toggle the locked status of all heat assignments for a specific heat.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `toggleLockedHeatsToggleLockedPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  toggleLockedHeatsToggleLockedPost(params: ToggleLockedHeatsToggleLockedPost$Params, context?: HttpContext): Observable<apiToggleResponse> {
    return this.toggleLockedHeatsToggleLockedPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiToggleResponse>): apiToggleResponse => r.body)
    );
  }

}
