/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAthletePrefsModel } from '../models/api-athlete-prefs-model';
import { apiAthletePrefsOutputModel } from '../models/api-athlete-prefs-output-model';
import { getAllAthletePrefsAthletePrefsAllGet } from '../fn/athlete-prefs/get-all-athlete-prefs-athlete-prefs-all-get';
import { GetAllAthletePrefsAthletePrefsAllGet$Params } from '../fn/athlete-prefs/get-all-athlete-prefs-athlete-prefs-all-get';
import { getAthletePrefsAthletePrefsCrossfitIdGet } from '../fn/athlete-prefs/get-athlete-prefs-athlete-prefs-crossfit-id-get';
import { GetAthletePrefsAthletePrefsCrossfitIdGet$Params } from '../fn/athlete-prefs/get-athlete-prefs-athlete-prefs-crossfit-id-get';
import { getMyPrefsAthletePrefsMeGet } from '../fn/athlete-prefs/get-my-prefs-athlete-prefs-me-get';
import { GetMyPrefsAthletePrefsMeGet$Params } from '../fn/athlete-prefs/get-my-prefs-athlete-prefs-me-get';
import { initializePrefsAthletePrefsInitializePost } from '../fn/athlete-prefs/initialize-prefs-athlete-prefs-initialize-post';
import { InitializePrefsAthletePrefsInitializePost$Params } from '../fn/athlete-prefs/initialize-prefs-athlete-prefs-initialize-post';
import { updateAthletePrefsAthletePrefsCrossfitIdPost } from '../fn/athlete-prefs/update-athlete-prefs-athlete-prefs-crossfit-id-post';
import { UpdateAthletePrefsAthletePrefsCrossfitIdPost$Params } from '../fn/athlete-prefs/update-athlete-prefs-athlete-prefs-crossfit-id-post';
import { updateMyPrefsAthletePrefsMePost } from '../fn/athlete-prefs/update-my-prefs-athlete-prefs-me-post';
import { UpdateMyPrefsAthletePrefsMePost$Params } from '../fn/athlete-prefs/update-my-prefs-athlete-prefs-me-post';

@Injectable({ providedIn: 'root' })
export class apiAthletePrefsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `initializePrefsAthletePrefsInitializePost()` */
  static readonly InitializePrefsAthletePrefsInitializePostPath = '/athlete-prefs/initialize';

  /**
   * Initialize Prefs.
   *
   * Initialize athlete preferences for 2025 from the athlete_prefs_2025 file.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initializePrefsAthletePrefsInitializePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializePrefsAthletePrefsInitializePost$Response(params?: InitializePrefsAthletePrefsInitializePost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return initializePrefsAthletePrefsInitializePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Initialize Prefs.
   *
   * Initialize athlete preferences for 2025 from the athlete_prefs_2025 file.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initializePrefsAthletePrefsInitializePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializePrefsAthletePrefsInitializePost(params?: InitializePrefsAthletePrefsInitializePost$Params, context?: HttpContext): Observable<{
}> {
    return this.initializePrefsAthletePrefsInitializePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getMyPrefsAthletePrefsMeGet()` */
  static readonly GetMyPrefsAthletePrefsMeGetPath = '/athlete-prefs/me';

  /**
   * Get My Prefs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyPrefsAthletePrefsMeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyPrefsAthletePrefsMeGet$Response(params?: GetMyPrefsAthletePrefsMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAthletePrefsModel>>> {
    return getMyPrefsAthletePrefsMeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get My Prefs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyPrefsAthletePrefsMeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyPrefsAthletePrefsMeGet(params?: GetMyPrefsAthletePrefsMeGet$Params, context?: HttpContext): Observable<Array<apiAthletePrefsModel>> {
    return this.getMyPrefsAthletePrefsMeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiAthletePrefsModel>>): Array<apiAthletePrefsModel> => r.body)
    );
  }

  /** Path part for operation `updateMyPrefsAthletePrefsMePost()` */
  static readonly UpdateMyPrefsAthletePrefsMePostPath = '/athlete-prefs/me';

  /**
   * Update My Prefs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMyPrefsAthletePrefsMePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyPrefsAthletePrefsMePost$Response(params: UpdateMyPrefsAthletePrefsMePost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return updateMyPrefsAthletePrefsMePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Update My Prefs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMyPrefsAthletePrefsMePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyPrefsAthletePrefsMePost(params: UpdateMyPrefsAthletePrefsMePost$Params, context?: HttpContext): Observable<any> {
    return this.updateMyPrefsAthletePrefsMePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

  /** Path part for operation `getAllAthletePrefsAthletePrefsAllGet()` */
  static readonly GetAllAthletePrefsAthletePrefsAllGetPath = '/athlete-prefs/all';

  /**
   * Get All Athlete Prefs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAthletePrefsAthletePrefsAllGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAthletePrefsAthletePrefsAllGet$Response(params: GetAllAthletePrefsAthletePrefsAllGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAthletePrefsOutputModel>>> {
    return getAllAthletePrefsAthletePrefsAllGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get All Athlete Prefs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAthletePrefsAthletePrefsAllGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAthletePrefsAthletePrefsAllGet(params: GetAllAthletePrefsAthletePrefsAllGet$Params, context?: HttpContext): Observable<Array<apiAthletePrefsOutputModel>> {
    return this.getAllAthletePrefsAthletePrefsAllGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiAthletePrefsOutputModel>>): Array<apiAthletePrefsOutputModel> => r.body)
    );
  }

  /** Path part for operation `getAthletePrefsAthletePrefsCrossfitIdGet()` */
  static readonly GetAthletePrefsAthletePrefsCrossfitIdGetPath = '/athlete-prefs/{crossfit_id}';

  /**
   * Get Athlete Prefs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAthletePrefsAthletePrefsCrossfitIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAthletePrefsAthletePrefsCrossfitIdGet$Response(params: GetAthletePrefsAthletePrefsCrossfitIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAthletePrefsModel>>> {
    return getAthletePrefsAthletePrefsCrossfitIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Athlete Prefs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAthletePrefsAthletePrefsCrossfitIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAthletePrefsAthletePrefsCrossfitIdGet(params: GetAthletePrefsAthletePrefsCrossfitIdGet$Params, context?: HttpContext): Observable<Array<apiAthletePrefsModel>> {
    return this.getAthletePrefsAthletePrefsCrossfitIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiAthletePrefsModel>>): Array<apiAthletePrefsModel> => r.body)
    );
  }

  /** Path part for operation `updateAthletePrefsAthletePrefsCrossfitIdPost()` */
  static readonly UpdateAthletePrefsAthletePrefsCrossfitIdPostPath = '/athlete-prefs/{crossfit_id}';

  /**
   * Update Athlete Prefs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAthletePrefsAthletePrefsCrossfitIdPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAthletePrefsAthletePrefsCrossfitIdPost$Response(params: UpdateAthletePrefsAthletePrefsCrossfitIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return updateAthletePrefsAthletePrefsCrossfitIdPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Athlete Prefs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAthletePrefsAthletePrefsCrossfitIdPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAthletePrefsAthletePrefsCrossfitIdPost(params: UpdateAthletePrefsAthletePrefsCrossfitIdPost$Params, context?: HttpContext): Observable<any> {
    return this.updateAthletePrefsAthletePrefsCrossfitIdPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
