/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adminRefreshCfGamesDataCfgamesAdminRefreshGet } from '../fn/cfgames/admin-refresh-cf-games-data-cfgames-admin-refresh-get';
import { AdminRefreshCfGamesDataCfgamesAdminRefreshGet$Params } from '../fn/cfgames/admin-refresh-cf-games-data-cfgames-admin-refresh-get';
import { apiCfDataCountModel } from '../models/api-cf-data-count-model';
import { apiCfGamesDataModel } from '../models/api-cf-games-data-model';
import { getAllCfGamesDataEndpointCfgamesDataAllGet } from '../fn/cfgames/get-all-cf-games-data-endpoint-cfgames-data-all-get';
import { GetAllCfGamesDataEndpointCfgamesDataAllGet$Params } from '../fn/cfgames/get-all-cf-games-data-endpoint-cfgames-data-all-get';
import { getCfGamesDataEndpointCfgamesDataAffiliateIdYearGet } from '../fn/cfgames/get-cf-games-data-endpoint-cfgames-data-affiliate-id-year-get';
import { GetCfGamesDataEndpointCfgamesDataAffiliateIdYearGet$Params } from '../fn/cfgames/get-cf-games-data-endpoint-cfgames-data-affiliate-id-year-get';

@Injectable({ providedIn: 'root' })
export class apiCfgamesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `adminRefreshCfGamesDataCfgamesAdminRefreshGet()` */
  static readonly AdminRefreshCfGamesDataCfgamesAdminRefreshGetPath = '/cfgames/admin-refresh';

  /**
   * Admin Refresh Cf Games Data.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminRefreshCfGamesDataCfgamesAdminRefreshGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminRefreshCfGamesDataCfgamesAdminRefreshGet$Response(params: AdminRefreshCfGamesDataCfgamesAdminRefreshGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiCfDataCountModel>> {
    return adminRefreshCfGamesDataCfgamesAdminRefreshGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Admin Refresh Cf Games Data.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminRefreshCfGamesDataCfgamesAdminRefreshGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminRefreshCfGamesDataCfgamesAdminRefreshGet(params: AdminRefreshCfGamesDataCfgamesAdminRefreshGet$Params, context?: HttpContext): Observable<apiCfDataCountModel> {
    return this.adminRefreshCfGamesDataCfgamesAdminRefreshGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiCfDataCountModel>): apiCfDataCountModel => r.body)
    );
  }

  /** Path part for operation `getAllCfGamesDataEndpointCfgamesDataAllGet()` */
  static readonly GetAllCfGamesDataEndpointCfgamesDataAllGetPath = '/cfgames/data/all';

  /**
   * Get All Cf Games Data Endpoint.
   *
   * Get all CF games data refresh timestamps.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCfGamesDataEndpointCfgamesDataAllGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCfGamesDataEndpointCfgamesDataAllGet$Response(params?: GetAllCfGamesDataEndpointCfgamesDataAllGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiCfGamesDataModel>>> {
    return getAllCfGamesDataEndpointCfgamesDataAllGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get All Cf Games Data Endpoint.
   *
   * Get all CF games data refresh timestamps.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCfGamesDataEndpointCfgamesDataAllGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCfGamesDataEndpointCfgamesDataAllGet(params?: GetAllCfGamesDataEndpointCfgamesDataAllGet$Params, context?: HttpContext): Observable<Array<apiCfGamesDataModel>> {
    return this.getAllCfGamesDataEndpointCfgamesDataAllGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiCfGamesDataModel>>): Array<apiCfGamesDataModel> => r.body)
    );
  }

  /** Path part for operation `getCfGamesDataEndpointCfgamesDataAffiliateIdYearGet()` */
  static readonly GetCfGamesDataEndpointCfgamesDataAffiliateIdYearGetPath = '/cfgames/data/{affiliate_id}/{year}/';

  /**
   * Get Cf Games Data Endpoint.
   *
   * Get CF games data refresh timestamp for a specific affiliate and year.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCfGamesDataEndpointCfgamesDataAffiliateIdYearGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCfGamesDataEndpointCfgamesDataAffiliateIdYearGet$Response(params: GetCfGamesDataEndpointCfgamesDataAffiliateIdYearGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiCfGamesDataModel>>> {
    return getCfGamesDataEndpointCfgamesDataAffiliateIdYearGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Cf Games Data Endpoint.
   *
   * Get CF games data refresh timestamp for a specific affiliate and year.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCfGamesDataEndpointCfgamesDataAffiliateIdYearGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCfGamesDataEndpointCfgamesDataAffiliateIdYearGet(params: GetCfGamesDataEndpointCfgamesDataAffiliateIdYearGet$Params, context?: HttpContext): Observable<Array<apiCfGamesDataModel>> {
    return this.getCfGamesDataEndpointCfgamesDataAffiliateIdYearGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiCfGamesDataModel>>): Array<apiCfGamesDataModel> => r.body)
    );
  }

}
