/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAthletePrefsModel } from '../models/api-athlete-prefs-model';
import { getAthletePrefsAthletePrefsGet } from '../fn/athlete-prefs/get-athlete-prefs-athlete-prefs-get';
import { GetAthletePrefsAthletePrefsGet$Params } from '../fn/athlete-prefs/get-athlete-prefs-athlete-prefs-get';

@Injectable({ providedIn: 'root' })
export class apiAthletePrefsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAthletePrefsAthletePrefsGet()` */
  static readonly GetAthletePrefsAthletePrefsGetPath = '/athlete-prefs/';

  /**
   * Get Athlete Prefs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAthletePrefsAthletePrefsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAthletePrefsAthletePrefsGet$Response(params: GetAthletePrefsAthletePrefsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAthletePrefsModel>>> {
    return getAthletePrefsAthletePrefsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Athlete Prefs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAthletePrefsAthletePrefsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAthletePrefsAthletePrefsGet(params: GetAthletePrefsAthletePrefsGet$Params, context?: HttpContext): Observable<Array<apiAthletePrefsModel>> {
    return this.getAthletePrefsAthletePrefsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiAthletePrefsModel>>): Array<apiAthletePrefsModel> => r.body)
    );
  }

}
