/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createNewJudgeJudgesPost } from '../fn/judges/create-new-judge-judges-post';
import { CreateNewJudgeJudgesPost$Params } from '../fn/judges/create-new-judge-judges-post';
import { deleteExistingJudgeJudgesJudgeIdDelete } from '../fn/judges/delete-existing-judge-judges-judge-id-delete';
import { DeleteExistingJudgeJudgesJudgeIdDelete$Params } from '../fn/judges/delete-existing-judge-judges-judge-id-delete';
import { getJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet } from '../fn/judges/get-judge-by-id-crossfit-judges-crossfit-id-crossfit-id-get';
import { GetJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet$Params } from '../fn/judges/get-judge-by-id-crossfit-judges-crossfit-id-crossfit-id-get';
import { getJudgeByIdJudgesJudgeIdGet } from '../fn/judges/get-judge-by-id-judges-judge-id-get';
import { GetJudgeByIdJudgesJudgeIdGet$Params } from '../fn/judges/get-judge-by-id-judges-judge-id-get';
import { getJudgesListJudgesGet } from '../fn/judges/get-judges-list-judges-get';
import { GetJudgesListJudgesGet$Params } from '../fn/judges/get-judges-list-judges-get';
import { initJudgesJudgesInitializePost } from '../fn/judges/init-judges-judges-initialize-post';
import { InitJudgesJudgesInitializePost$Params } from '../fn/judges/init-judges-judges-initialize-post';
import { apiJudgesModel } from '../models/api-judges-model';
import { updateExistingJudgeJudgesJudgeIdPatch } from '../fn/judges/update-existing-judge-judges-judge-id-patch';
import { UpdateExistingJudgeJudgesJudgeIdPatch$Params } from '../fn/judges/update-existing-judge-judges-judge-id-patch';

@Injectable({ providedIn: 'root' })
export class apiJudgesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getJudgesListJudgesGet()` */
  static readonly GetJudgesListJudgesGetPath = '/judges/';

  /**
   * Get Judges List.
   *
   * Get all judges.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJudgesListJudgesGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJudgesListJudgesGet$Response(params?: GetJudgesListJudgesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiJudgesModel>>> {
    return getJudgesListJudgesGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Judges List.
   *
   * Get all judges.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJudgesListJudgesGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJudgesListJudgesGet(params?: GetJudgesListJudgesGet$Params, context?: HttpContext): Observable<Array<apiJudgesModel>> {
    return this.getJudgesListJudgesGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiJudgesModel>>): Array<apiJudgesModel> => r.body)
    );
  }

  /** Path part for operation `createNewJudgeJudgesPost()` */
  static readonly CreateNewJudgeJudgesPostPath = '/judges/';

  /**
   * Create New Judge.
   *
   * Create a new judge.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createNewJudgeJudgesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewJudgeJudgesPost$Response(params: CreateNewJudgeJudgesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgesModel>> {
    return createNewJudgeJudgesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create New Judge.
   *
   * Create a new judge.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createNewJudgeJudgesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewJudgeJudgesPost(params: CreateNewJudgeJudgesPost$Params, context?: HttpContext): Observable<apiJudgesModel> {
    return this.createNewJudgeJudgesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiJudgesModel>): apiJudgesModel => r.body)
    );
  }

  /** Path part for operation `getJudgeByIdJudgesJudgeIdGet()` */
  static readonly GetJudgeByIdJudgesJudgeIdGetPath = '/judges/{judge_id}';

  /**
   * Get Judge By Id.
   *
   * Get a judge by ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJudgeByIdJudgesJudgeIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJudgeByIdJudgesJudgeIdGet$Response(params: GetJudgeByIdJudgesJudgeIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgesModel>> {
    return getJudgeByIdJudgesJudgeIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Judge By Id.
   *
   * Get a judge by ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJudgeByIdJudgesJudgeIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJudgeByIdJudgesJudgeIdGet(params: GetJudgeByIdJudgesJudgeIdGet$Params, context?: HttpContext): Observable<apiJudgesModel> {
    return this.getJudgeByIdJudgesJudgeIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiJudgesModel>): apiJudgesModel => r.body)
    );
  }

  /** Path part for operation `deleteExistingJudgeJudgesJudgeIdDelete()` */
  static readonly DeleteExistingJudgeJudgesJudgeIdDeletePath = '/judges/{judge_id}';

  /**
   * Delete Existing Judge.
   *
   * Delete a judge.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteExistingJudgeJudgesJudgeIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExistingJudgeJudgesJudgeIdDelete$Response(params: DeleteExistingJudgeJudgesJudgeIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteExistingJudgeJudgesJudgeIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Existing Judge.
   *
   * Delete a judge.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteExistingJudgeJudgesJudgeIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExistingJudgeJudgesJudgeIdDelete(params: DeleteExistingJudgeJudgesJudgeIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.deleteExistingJudgeJudgesJudgeIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateExistingJudgeJudgesJudgeIdPatch()` */
  static readonly UpdateExistingJudgeJudgesJudgeIdPatchPath = '/judges/{judge_id}';

  /**
   * Update Existing Judge.
   *
   * Update an existing judge.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateExistingJudgeJudgesJudgeIdPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExistingJudgeJudgesJudgeIdPatch$Response(params: UpdateExistingJudgeJudgesJudgeIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgesModel>> {
    return updateExistingJudgeJudgesJudgeIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Existing Judge.
   *
   * Update an existing judge.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateExistingJudgeJudgesJudgeIdPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExistingJudgeJudgesJudgeIdPatch(params: UpdateExistingJudgeJudgesJudgeIdPatch$Params, context?: HttpContext): Observable<apiJudgesModel> {
    return this.updateExistingJudgeJudgesJudgeIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiJudgesModel>): apiJudgesModel => r.body)
    );
  }

  /** Path part for operation `getJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet()` */
  static readonly GetJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGetPath = '/judges/crossfit_id/{crossfit_id}';

  /**
   * Get Judge By Id Crossfit.
   *
   * Get a judge by crossfit_id.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet$Response(params: GetJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgesModel>> {
    return getJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Judge By Id Crossfit.
   *
   * Get a judge by crossfit_id.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet(params: GetJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet$Params, context?: HttpContext): Observable<apiJudgesModel> {
    return this.getJudgeByIdCrossfitJudgesCrossfitIdCrossfitIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiJudgesModel>): apiJudgesModel => r.body)
    );
  }

  /** Path part for operation `initJudgesJudgesInitializePost()` */
  static readonly InitJudgesJudgesInitializePostPath = '/judges/initialize';

  /**
   * Init Judges.
   *
   * Initialize judge information for all athletes based on scoring history.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initJudgesJudgesInitializePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  initJudgesJudgesInitializePost$Response(params?: InitJudgesJudgesInitializePost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
    return initJudgesJudgesInitializePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Init Judges.
   *
   * Initialize judge information for all athletes based on scoring history.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initJudgesJudgesInitializePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initJudgesJudgesInitializePost(params?: InitJudgesJudgesInitializePost$Params, context?: HttpContext): Observable<{
[key: string]: string;
}> {
    return this.initJudgesJudgesInitializePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: string;
}>): {
[key: string]: string;
} => r.body)
    );
  }

}
