/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { applyIndividualSideScoresEndpointIndividualSideScoreApplyPost } from '../fn/individual-side-score/apply-individual-side-scores-endpoint-individual-side-score-apply-post';
import { ApplyIndividualSideScoresEndpointIndividualSideScoreApplyPost$Params } from '../fn/individual-side-score/apply-individual-side-scores-endpoint-individual-side-score-apply-post';
import { deleteIndividualSideScoresIndividualSideScoreDelete } from '../fn/individual-side-score/delete-individual-side-scores-individual-side-score-delete';
import { DeleteIndividualSideScoresIndividualSideScoreDelete$Params } from '../fn/individual-side-score/delete-individual-side-scores-individual-side-score-delete';
import { getIndividualSideScoresIndividualSideScoreAffiliateIdYearGet } from '../fn/individual-side-score/get-individual-side-scores-individual-side-score-affiliate-id-year-get';
import { GetIndividualSideScoresIndividualSideScoreAffiliateIdYearGet$Params } from '../fn/individual-side-score/get-individual-side-scores-individual-side-score-affiliate-id-year-get';
import { apiIndividualSideScoreModel } from '../models/api-individual-side-score-model';
import { updateIndividualSideScoresIndividualSideScorePost } from '../fn/individual-side-score/update-individual-side-scores-individual-side-score-post';
import { UpdateIndividualSideScoresIndividualSideScorePost$Params } from '../fn/individual-side-score/update-individual-side-scores-individual-side-score-post';

@Injectable({ providedIn: 'root' })
export class apiIndividualSideScoreService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getIndividualSideScoresIndividualSideScoreAffiliateIdYearGet()` */
  static readonly GetIndividualSideScoresIndividualSideScoreAffiliateIdYearGetPath = '/individual_side_score/{affiliate_id}/{year}/';

  /**
   * Get Individual Side Scores.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getIndividualSideScoresIndividualSideScoreAffiliateIdYearGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIndividualSideScoresIndividualSideScoreAffiliateIdYearGet$Response(params: GetIndividualSideScoresIndividualSideScoreAffiliateIdYearGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiIndividualSideScoreModel>>> {
    return getIndividualSideScoresIndividualSideScoreAffiliateIdYearGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Individual Side Scores.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getIndividualSideScoresIndividualSideScoreAffiliateIdYearGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIndividualSideScoresIndividualSideScoreAffiliateIdYearGet(params: GetIndividualSideScoresIndividualSideScoreAffiliateIdYearGet$Params, context?: HttpContext): Observable<Array<apiIndividualSideScoreModel>> {
    return this.getIndividualSideScoresIndividualSideScoreAffiliateIdYearGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiIndividualSideScoreModel>>): Array<apiIndividualSideScoreModel> => r.body)
    );
  }

  /** Path part for operation `updateIndividualSideScoresIndividualSideScorePost()` */
  static readonly UpdateIndividualSideScoresIndividualSideScorePostPath = '/individual_side_score/';

  /**
   * Update Individual Side Scores.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateIndividualSideScoresIndividualSideScorePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateIndividualSideScoresIndividualSideScorePost$Response(params: UpdateIndividualSideScoresIndividualSideScorePost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return updateIndividualSideScoresIndividualSideScorePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Individual Side Scores.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateIndividualSideScoresIndividualSideScorePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateIndividualSideScoresIndividualSideScorePost(params: UpdateIndividualSideScoresIndividualSideScorePost$Params, context?: HttpContext): Observable<any> {
    return this.updateIndividualSideScoresIndividualSideScorePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

  /** Path part for operation `deleteIndividualSideScoresIndividualSideScoreDelete()` */
  static readonly DeleteIndividualSideScoresIndividualSideScoreDeletePath = '/individual_side_score/';

  /**
   * Delete Individual Side Scores.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteIndividualSideScoresIndividualSideScoreDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteIndividualSideScoresIndividualSideScoreDelete$Response(params: DeleteIndividualSideScoresIndividualSideScoreDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteIndividualSideScoresIndividualSideScoreDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Individual Side Scores.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteIndividualSideScoresIndividualSideScoreDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteIndividualSideScoresIndividualSideScoreDelete(params: DeleteIndividualSideScoresIndividualSideScoreDelete$Params, context?: HttpContext): Observable<void> {
    return this.deleteIndividualSideScoresIndividualSideScoreDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `applyIndividualSideScoresEndpointIndividualSideScoreApplyPost()` */
  static readonly ApplyIndividualSideScoresEndpointIndividualSideScoreApplyPostPath = '/individual_side_score/apply';

  /**
   * Apply Individual Side Scores Endpoint.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `applyIndividualSideScoresEndpointIndividualSideScoreApplyPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  applyIndividualSideScoresEndpointIndividualSideScoreApplyPost$Response(params: ApplyIndividualSideScoresEndpointIndividualSideScoreApplyPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return applyIndividualSideScoresEndpointIndividualSideScoreApplyPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Apply Individual Side Scores Endpoint.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `applyIndividualSideScoresEndpointIndividualSideScoreApplyPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  applyIndividualSideScoresEndpointIndividualSideScoreApplyPost(params: ApplyIndividualSideScoresEndpointIndividualSideScoreApplyPost$Params, context?: HttpContext): Observable<any> {
    return this.applyIndividualSideScoresEndpointIndividualSideScoreApplyPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

}
