/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assignAthletesAndJudgesHeatAssignmentsAssignRandomPost } from '../fn/heat-assignments/assign-athletes-and-judges-heat-assignments-assign-random-post';
import { AssignAthletesAndJudgesHeatAssignmentsAssignRandomPost$Params } from '../fn/heat-assignments/assign-athletes-and-judges-heat-assignments-assign-random-post';
import { assignAthletesHeatAssignmentsAssignAthletesPost } from '../fn/heat-assignments/assign-athletes-heat-assignments-assign-athletes-post';
import { AssignAthletesHeatAssignmentsAssignAthletesPost$Params } from '../fn/heat-assignments/assign-athletes-heat-assignments-assign-athletes-post';
import { apiAssignAthletesResponse } from '../models/api-assign-athletes-response';
import { assignJudgesHeatAssignmentsAssignJudgesPost } from '../fn/heat-assignments/assign-judges-heat-assignments-assign-judges-post';
import { AssignJudgesHeatAssignmentsAssignJudgesPost$Params } from '../fn/heat-assignments/assign-judges-heat-assignments-assign-judges-post';
import { apiAssignJudgesResponse } from '../models/api-assign-judges-response';
import { clearAthleteHeatAssignmentsAssignmentIdClearAthletePatch } from '../fn/heat-assignments/clear-athlete-heat-assignments-assignment-id-clear-athlete-patch';
import { ClearAthleteHeatAssignmentsAssignmentIdClearAthletePatch$Params } from '../fn/heat-assignments/clear-athlete-heat-assignments-assignment-id-clear-athlete-patch';
import { clearJudgeHeatAssignmentsAssignmentIdClearJudgePatch } from '../fn/heat-assignments/clear-judge-heat-assignments-assignment-id-clear-judge-patch';
import { ClearJudgeHeatAssignmentsAssignmentIdClearJudgePatch$Params } from '../fn/heat-assignments/clear-judge-heat-assignments-assignment-id-clear-judge-patch';
import { createNewHeatAssignmentHeatAssignmentsPost } from '../fn/heat-assignments/create-new-heat-assignment-heat-assignments-post';
import { CreateNewHeatAssignmentHeatAssignmentsPost$Params } from '../fn/heat-assignments/create-new-heat-assignment-heat-assignments-post';
import { deleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost } from '../fn/heat-assignments/delete-assignments-by-criteria-heat-assignments-delete-by-criteria-post';
import { DeleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost$Params } from '../fn/heat-assignments/delete-assignments-by-criteria-heat-assignments-delete-by-criteria-post';
import { apiDeleteAssignmentsByCriteriaResponse } from '../models/api-delete-assignments-by-criteria-response';
import { deleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete } from '../fn/heat-assignments/delete-existing-heat-assignment-heat-assignments-assignment-id-delete';
import { DeleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete$Params } from '../fn/heat-assignments/delete-existing-heat-assignment-heat-assignments-assignment-id-delete';
import { deleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost } from '../fn/heat-assignments/delete-unlocked-assignments-heat-assignments-delete-unlocked-post';
import { DeleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost$Params } from '../fn/heat-assignments/delete-unlocked-assignments-heat-assignments-delete-unlocked-post';
import { getHeatAssignmentByIdHeatAssignmentsAssignmentIdGet } from '../fn/heat-assignments/get-heat-assignment-by-id-heat-assignments-assignment-id-get';
import { GetHeatAssignmentByIdHeatAssignmentsAssignmentIdGet$Params } from '../fn/heat-assignments/get-heat-assignment-by-id-heat-assignments-assignment-id-get';
import { getHeatAssignmentsListHeatAssignmentsGet } from '../fn/heat-assignments/get-heat-assignments-list-heat-assignments-get';
import { GetHeatAssignmentsListHeatAssignmentsGet$Params } from '../fn/heat-assignments/get-heat-assignments-list-heat-assignments-get';
import { getHeatAttendanceHeatAssignmentsHeatAttendanceGet } from '../fn/heat-assignments/get-heat-attendance-heat-assignments-heat-attendance-get';
import { GetHeatAttendanceHeatAssignmentsHeatAttendanceGet$Params } from '../fn/heat-assignments/get-heat-attendance-heat-assignments-heat-attendance-get';
import { getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet } from '../fn/heat-assignments/get-my-heat-assignments-athlete-heat-assignments-me-athlete-get';
import { GetMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet$Params } from '../fn/heat-assignments/get-my-heat-assignments-athlete-heat-assignments-me-athlete-get';
import { getMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet } from '../fn/heat-assignments/get-my-heat-assignments-judge-heat-assignments-me-judge-get';
import { GetMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet$Params } from '../fn/heat-assignments/get-my-heat-assignments-judge-heat-assignments-me-judge-get';
import { apiHeatAssignmentModel } from '../models/api-heat-assignment-model';
import { apiHeatAttendanceModel } from '../models/api-heat-attendance-model';
import { apiRandomAssignmentResponse } from '../models/api-random-assignment-response';
import { updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch } from '../fn/heat-assignments/update-existing-heat-assignment-heat-assignments-assignment-id-patch';
import { UpdateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch$Params } from '../fn/heat-assignments/update-existing-heat-assignment-heat-assignments-assignment-id-patch';

@Injectable({ providedIn: 'root' })
export class apiHeatAssignmentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet()` */
  static readonly GetMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGetPath = '/heat_assignments/me-athlete';

  /**
   * Get My Heat Assignments Athlete.
   *
   * Get heat assignments for the authenticated athlete.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet$Response(params: GetMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatAssignmentModel>> {
    return getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get My Heat Assignments Athlete.
   *
   * Get heat assignments for the authenticated athlete.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet(params: GetMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet$Params, context?: HttpContext): Observable<apiHeatAssignmentModel> {
    return this.getMyHeatAssignmentsAthleteHeatAssignmentsMeAthleteGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatAssignmentModel>): apiHeatAssignmentModel => r.body)
    );
  }

  /** Path part for operation `getMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet()` */
  static readonly GetMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGetPath = '/heat_assignments/me-judge';

  /**
   * Get My Heat Assignments Judge.
   *
   * Get heat assignments for the authenticated judge.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet$Response(params: GetMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatAssignmentModel>>> {
    return getMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get My Heat Assignments Judge.
   *
   * Get heat assignments for the authenticated judge.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet(params: GetMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet$Params, context?: HttpContext): Observable<Array<apiHeatAssignmentModel>> {
    return this.getMyHeatAssignmentsJudgeHeatAssignmentsMeJudgeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiHeatAssignmentModel>>): Array<apiHeatAssignmentModel> => r.body)
    );
  }

  /** Path part for operation `getHeatAssignmentsListHeatAssignmentsGet()` */
  static readonly GetHeatAssignmentsListHeatAssignmentsGetPath = '/heat_assignments/';

  /**
   * Get Heat Assignments List.
   *
   * Get all heat assignments, optionally filtered by heat_id.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHeatAssignmentsListHeatAssignmentsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatAssignmentsListHeatAssignmentsGet$Response(params?: GetHeatAssignmentsListHeatAssignmentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatAssignmentModel>>> {
    return getHeatAssignmentsListHeatAssignmentsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Heat Assignments List.
   *
   * Get all heat assignments, optionally filtered by heat_id.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHeatAssignmentsListHeatAssignmentsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatAssignmentsListHeatAssignmentsGet(params?: GetHeatAssignmentsListHeatAssignmentsGet$Params, context?: HttpContext): Observable<Array<apiHeatAssignmentModel>> {
    return this.getHeatAssignmentsListHeatAssignmentsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiHeatAssignmentModel>>): Array<apiHeatAssignmentModel> => r.body)
    );
  }

  /** Path part for operation `createNewHeatAssignmentHeatAssignmentsPost()` */
  static readonly CreateNewHeatAssignmentHeatAssignmentsPostPath = '/heat_assignments/';

  /**
   * Create New Heat Assignment.
   *
   * Create a new heat assignment.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createNewHeatAssignmentHeatAssignmentsPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewHeatAssignmentHeatAssignmentsPost$Response(params: CreateNewHeatAssignmentHeatAssignmentsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatAssignmentModel>> {
    return createNewHeatAssignmentHeatAssignmentsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create New Heat Assignment.
   *
   * Create a new heat assignment.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createNewHeatAssignmentHeatAssignmentsPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewHeatAssignmentHeatAssignmentsPost(params: CreateNewHeatAssignmentHeatAssignmentsPost$Params, context?: HttpContext): Observable<apiHeatAssignmentModel> {
    return this.createNewHeatAssignmentHeatAssignmentsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatAssignmentModel>): apiHeatAssignmentModel => r.body)
    );
  }

  /** Path part for operation `getHeatAttendanceHeatAssignmentsHeatAttendanceGet()` */
  static readonly GetHeatAttendanceHeatAssignmentsHeatAttendanceGetPath = '/heat_assignments/heat-attendance';

  /**
   * Get Heat Attendance.
   *
   * Get heat attendance for a specific affiliate and year.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHeatAttendanceHeatAssignmentsHeatAttendanceGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatAttendanceHeatAssignmentsHeatAttendanceGet$Response(params: GetHeatAttendanceHeatAssignmentsHeatAttendanceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatAttendanceModel>>> {
    return getHeatAttendanceHeatAssignmentsHeatAttendanceGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Heat Attendance.
   *
   * Get heat attendance for a specific affiliate and year.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHeatAttendanceHeatAssignmentsHeatAttendanceGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatAttendanceHeatAssignmentsHeatAttendanceGet(params: GetHeatAttendanceHeatAssignmentsHeatAttendanceGet$Params, context?: HttpContext): Observable<Array<apiHeatAttendanceModel>> {
    return this.getHeatAttendanceHeatAssignmentsHeatAttendanceGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiHeatAttendanceModel>>): Array<apiHeatAttendanceModel> => r.body)
    );
  }

  /** Path part for operation `getHeatAssignmentByIdHeatAssignmentsAssignmentIdGet()` */
  static readonly GetHeatAssignmentByIdHeatAssignmentsAssignmentIdGetPath = '/heat_assignments/{assignment_id}';

  /**
   * Get Heat Assignment By Id.
   *
   * Get a heat assignment by ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHeatAssignmentByIdHeatAssignmentsAssignmentIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatAssignmentByIdHeatAssignmentsAssignmentIdGet$Response(params: GetHeatAssignmentByIdHeatAssignmentsAssignmentIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatAssignmentModel>> {
    return getHeatAssignmentByIdHeatAssignmentsAssignmentIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Heat Assignment By Id.
   *
   * Get a heat assignment by ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHeatAssignmentByIdHeatAssignmentsAssignmentIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatAssignmentByIdHeatAssignmentsAssignmentIdGet(params: GetHeatAssignmentByIdHeatAssignmentsAssignmentIdGet$Params, context?: HttpContext): Observable<apiHeatAssignmentModel> {
    return this.getHeatAssignmentByIdHeatAssignmentsAssignmentIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatAssignmentModel>): apiHeatAssignmentModel => r.body)
    );
  }

  /** Path part for operation `deleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete()` */
  static readonly DeleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDeletePath = '/heat_assignments/{assignment_id}';

  /**
   * Delete Existing Heat Assignment.
   *
   * Delete a heat assignment.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete$Response(params: DeleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Existing Heat Assignment.
   *
   * Delete a heat assignment.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete(params: DeleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.deleteExistingHeatAssignmentHeatAssignmentsAssignmentIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch()` */
  static readonly UpdateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatchPath = '/heat_assignments/{assignment_id}';

  /**
   * Update Existing Heat Assignment.
   *
   * Update an existing heat assignment.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch$Response(params: UpdateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatAssignmentModel>> {
    return updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Existing Heat Assignment.
   *
   * Update an existing heat assignment.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch(params: UpdateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch$Params, context?: HttpContext): Observable<apiHeatAssignmentModel> {
    return this.updateExistingHeatAssignmentHeatAssignmentsAssignmentIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatAssignmentModel>): apiHeatAssignmentModel => r.body)
    );
  }

  /** Path part for operation `clearAthleteHeatAssignmentsAssignmentIdClearAthletePatch()` */
  static readonly ClearAthleteHeatAssignmentsAssignmentIdClearAthletePatchPath = '/heat_assignments/{assignment_id}/clear-athlete';

  /**
   * Clear Athlete.
   *
   * Clear the athlete assignment from a heat assignment.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clearAthleteHeatAssignmentsAssignmentIdClearAthletePatch()` instead.
   *
   * This method doesn't expect any request body.
   */
  clearAthleteHeatAssignmentsAssignmentIdClearAthletePatch$Response(params: ClearAthleteHeatAssignmentsAssignmentIdClearAthletePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatAssignmentModel>> {
    return clearAthleteHeatAssignmentsAssignmentIdClearAthletePatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Clear Athlete.
   *
   * Clear the athlete assignment from a heat assignment.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clearAthleteHeatAssignmentsAssignmentIdClearAthletePatch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clearAthleteHeatAssignmentsAssignmentIdClearAthletePatch(params: ClearAthleteHeatAssignmentsAssignmentIdClearAthletePatch$Params, context?: HttpContext): Observable<apiHeatAssignmentModel> {
    return this.clearAthleteHeatAssignmentsAssignmentIdClearAthletePatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatAssignmentModel>): apiHeatAssignmentModel => r.body)
    );
  }

  /** Path part for operation `clearJudgeHeatAssignmentsAssignmentIdClearJudgePatch()` */
  static readonly ClearJudgeHeatAssignmentsAssignmentIdClearJudgePatchPath = '/heat_assignments/{assignment_id}/clear-judge';

  /**
   * Clear Judge.
   *
   * Clear the judge assignment from a heat assignment.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `clearJudgeHeatAssignmentsAssignmentIdClearJudgePatch()` instead.
   *
   * This method doesn't expect any request body.
   */
  clearJudgeHeatAssignmentsAssignmentIdClearJudgePatch$Response(params: ClearJudgeHeatAssignmentsAssignmentIdClearJudgePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatAssignmentModel>> {
    return clearJudgeHeatAssignmentsAssignmentIdClearJudgePatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Clear Judge.
   *
   * Clear the judge assignment from a heat assignment.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `clearJudgeHeatAssignmentsAssignmentIdClearJudgePatch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  clearJudgeHeatAssignmentsAssignmentIdClearJudgePatch(params: ClearJudgeHeatAssignmentsAssignmentIdClearJudgePatch$Params, context?: HttpContext): Observable<apiHeatAssignmentModel> {
    return this.clearJudgeHeatAssignmentsAssignmentIdClearJudgePatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatAssignmentModel>): apiHeatAssignmentModel => r.body)
    );
  }

  /** Path part for operation `assignAthletesAndJudgesHeatAssignmentsAssignRandomPost()` */
  static readonly AssignAthletesAndJudgesHeatAssignmentsAssignRandomPostPath = '/heat_assignments/assign-random';

  /**
   * Assign Athletes And Judges.
   *
   * Randomly assign athletes and judges to heats based on preferences.
   *
   * DEPRECATED: Use /assign-athletes and /assign-judges endpoints instead.
   *
   * Rules:
   * - Athletes with "NA" at preference_nbr 0 are skipped
   * - Judges are assigned as athletes first (priority)
   * - Judges cannot be assigned to judge heats within 45 minutes of their athlete assignments
   * - Respects max_athletes limit of each heat
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignAthletesAndJudgesHeatAssignmentsAssignRandomPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignAthletesAndJudgesHeatAssignmentsAssignRandomPost$Response(params: AssignAthletesAndJudgesHeatAssignmentsAssignRandomPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiRandomAssignmentResponse>> {
    return assignAthletesAndJudgesHeatAssignmentsAssignRandomPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Assign Athletes And Judges.
   *
   * Randomly assign athletes and judges to heats based on preferences.
   *
   * DEPRECATED: Use /assign-athletes and /assign-judges endpoints instead.
   *
   * Rules:
   * - Athletes with "NA" at preference_nbr 0 are skipped
   * - Judges are assigned as athletes first (priority)
   * - Judges cannot be assigned to judge heats within 45 minutes of their athlete assignments
   * - Respects max_athletes limit of each heat
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignAthletesAndJudgesHeatAssignmentsAssignRandomPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignAthletesAndJudgesHeatAssignmentsAssignRandomPost(params: AssignAthletesAndJudgesHeatAssignmentsAssignRandomPost$Params, context?: HttpContext): Observable<apiRandomAssignmentResponse> {
    return this.assignAthletesAndJudgesHeatAssignmentsAssignRandomPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiRandomAssignmentResponse>): apiRandomAssignmentResponse => r.body)
    );
  }

  /** Path part for operation `assignAthletesHeatAssignmentsAssignAthletesPost()` */
  static readonly AssignAthletesHeatAssignmentsAssignAthletesPostPath = '/heat_assignments/assign-athletes';

  /**
   * Assign Athletes.
   *
   * Randomly assign athletes to heats based on their time preferences.
   *
   * Rules:
   * - Athletes with "NA" at preference_nbr 0 are skipped
   * - Preferred athletes are assigned first using their start_time preferences
   * - Preferred judges (as athletes) are assigned next
   * - Regular athletes (including non-preferred judges) are assigned last
   * - Respects max_athletes limit of each heat
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignAthletesHeatAssignmentsAssignAthletesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignAthletesHeatAssignmentsAssignAthletesPost$Response(params: AssignAthletesHeatAssignmentsAssignAthletesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAssignAthletesResponse>> {
    return assignAthletesHeatAssignmentsAssignAthletesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Assign Athletes.
   *
   * Randomly assign athletes to heats based on their time preferences.
   *
   * Rules:
   * - Athletes with "NA" at preference_nbr 0 are skipped
   * - Preferred athletes are assigned first using their start_time preferences
   * - Preferred judges (as athletes) are assigned next
   * - Regular athletes (including non-preferred judges) are assigned last
   * - Respects max_athletes limit of each heat
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignAthletesHeatAssignmentsAssignAthletesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignAthletesHeatAssignmentsAssignAthletesPost(params: AssignAthletesHeatAssignmentsAssignAthletesPost$Params, context?: HttpContext): Observable<apiAssignAthletesResponse> {
    return this.assignAthletesHeatAssignmentsAssignAthletesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiAssignAthletesResponse>): apiAssignAthletesResponse => r.body)
    );
  }

  /** Path part for operation `assignJudgesHeatAssignmentsAssignJudgesPost()` */
  static readonly AssignJudgesHeatAssignmentsAssignJudgesPostPath = '/heat_assignments/assign-judges';

  /**
   * Assign Judges.
   *
   * Randomly assign judges to heats based on judge availability and athlete assignments.
   *
   * Rules:
   * - Ensures judges are not assigned to judge heats within 45 minutes of their athlete assignments
   * - Prefers assigning judges who have marked themselves as available for that time slot
   * - Distributes assignments evenly among preferred judges
   * - Avoids back-to-back judge assignments
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignJudgesHeatAssignmentsAssignJudgesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignJudgesHeatAssignmentsAssignJudgesPost$Response(params: AssignJudgesHeatAssignmentsAssignJudgesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAssignJudgesResponse>> {
    return assignJudgesHeatAssignmentsAssignJudgesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Assign Judges.
   *
   * Randomly assign judges to heats based on judge availability and athlete assignments.
   *
   * Rules:
   * - Ensures judges are not assigned to judge heats within 45 minutes of their athlete assignments
   * - Prefers assigning judges who have marked themselves as available for that time slot
   * - Distributes assignments evenly among preferred judges
   * - Avoids back-to-back judge assignments
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignJudgesHeatAssignmentsAssignJudgesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignJudgesHeatAssignmentsAssignJudgesPost(params: AssignJudgesHeatAssignmentsAssignJudgesPost$Params, context?: HttpContext): Observable<apiAssignJudgesResponse> {
    return this.assignJudgesHeatAssignmentsAssignJudgesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiAssignJudgesResponse>): apiAssignJudgesResponse => r.body)
    );
  }

  /** Path part for operation `deleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost()` */
  static readonly DeleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPostPath = '/heat_assignments/delete-by-criteria';

  /**
   * Delete Assignments By Criteria.
   *
   * Delete all heat assignments for a specific affiliate, year, and ordinal.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost$Response(params: DeleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiDeleteAssignmentsByCriteriaResponse>> {
    return deleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Assignments By Criteria.
   *
   * Delete all heat assignments for a specific affiliate, year, and ordinal.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost(params: DeleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost$Params, context?: HttpContext): Observable<apiDeleteAssignmentsByCriteriaResponse> {
    return this.deleteAssignmentsByCriteriaHeatAssignmentsDeleteByCriteriaPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiDeleteAssignmentsByCriteriaResponse>): apiDeleteAssignmentsByCriteriaResponse => r.body)
    );
  }

  /** Path part for operation `deleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost()` */
  static readonly DeleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPostPath = '/heat_assignments/delete-unlocked';

  /**
   * Delete Unlocked Assignments.
   *
   * Delete unlocked heat assignments for a specific affiliate, year, and ordinal.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost$Response(params: DeleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiDeleteAssignmentsByCriteriaResponse>> {
    return deleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Unlocked Assignments.
   *
   * Delete unlocked heat assignments for a specific affiliate, year, and ordinal.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost(params: DeleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost$Params, context?: HttpContext): Observable<apiDeleteAssignmentsByCriteriaResponse> {
    return this.deleteUnlockedAssignmentsHeatAssignmentsDeleteUnlockedPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiDeleteAssignmentsByCriteriaResponse>): apiDeleteAssignmentsByCriteriaResponse => r.body)
    );
  }

}
