/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createPreferredAthleteEntryPreferredAthletesPost } from '../fn/preferred-athletes/create-preferred-athlete-entry-preferred-athletes-post';
import { CreatePreferredAthleteEntryPreferredAthletesPost$Params } from '../fn/preferred-athletes/create-preferred-athlete-entry-preferred-athletes-post';
import { deletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete } from '../fn/preferred-athletes/delete-preferred-athlete-entry-preferred-athletes-affiliate-id-crossfit-id-delete';
import { DeletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete$Params } from '../fn/preferred-athletes/delete-preferred-athlete-entry-preferred-athletes-affiliate-id-crossfit-id-delete';
import { getPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet } from '../fn/preferred-athletes/get-preferred-athlete-by-id-preferred-athletes-affiliate-id-crossfit-id-get';
import { GetPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet$Params } from '../fn/preferred-athletes/get-preferred-athlete-by-id-preferred-athletes-affiliate-id-crossfit-id-get';
import { initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost } from '../fn/preferred-athletes/initialize-preferred-athletes-preferred-athletes-affiliate-id-initialize-post';
import { InitializePreferredAthletesPreferredAthletesAffiliateIdInitializePost$Params } from '../fn/preferred-athletes/initialize-preferred-athletes-preferred-athletes-affiliate-id-initialize-post';
import { listPreferredAthletesPreferredAthletesAffiliateIdGet } from '../fn/preferred-athletes/list-preferred-athletes-preferred-athletes-affiliate-id-get';
import { ListPreferredAthletesPreferredAthletesAffiliateIdGet$Params } from '../fn/preferred-athletes/list-preferred-athletes-preferred-athletes-affiliate-id-get';
import { apiPreferredAthleteModel } from '../models/api-preferred-athlete-model';
import { apiPreferredAthletesInitResponse } from '../models/api-preferred-athletes-init-response';
import { updatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch } from '../fn/preferred-athletes/update-preferred-athlete-entry-preferred-athletes-affiliate-id-crossfit-id-patch';
import { UpdatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch$Params } from '../fn/preferred-athletes/update-preferred-athlete-entry-preferred-athletes-affiliate-id-crossfit-id-patch';

@Injectable({ providedIn: 'root' })
export class apiPreferredAthletesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listPreferredAthletesPreferredAthletesAffiliateIdGet()` */
  static readonly ListPreferredAthletesPreferredAthletesAffiliateIdGetPath = '/preferred_athletes/{affiliate_id}';

  /**
   * List Preferred Athletes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listPreferredAthletesPreferredAthletesAffiliateIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  listPreferredAthletesPreferredAthletesAffiliateIdGet$Response(params: ListPreferredAthletesPreferredAthletesAffiliateIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiPreferredAthleteModel>>> {
    return listPreferredAthletesPreferredAthletesAffiliateIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * List Preferred Athletes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listPreferredAthletesPreferredAthletesAffiliateIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listPreferredAthletesPreferredAthletesAffiliateIdGet(params: ListPreferredAthletesPreferredAthletesAffiliateIdGet$Params, context?: HttpContext): Observable<Array<apiPreferredAthleteModel>> {
    return this.listPreferredAthletesPreferredAthletesAffiliateIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiPreferredAthleteModel>>): Array<apiPreferredAthleteModel> => r.body)
    );
  }

  /** Path part for operation `getPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet()` */
  static readonly GetPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGetPath = '/preferred_athletes/{affiliate_id}/{crossfit_id}';

  /**
   * Get Preferred Athlete By Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet$Response(params: GetPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiPreferredAthleteModel>> {
    return getPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Preferred Athlete By Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet(params: GetPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet$Params, context?: HttpContext): Observable<apiPreferredAthleteModel> {
    return this.getPreferredAthleteByIdPreferredAthletesAffiliateIdCrossfitIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiPreferredAthleteModel>): apiPreferredAthleteModel => r.body)
    );
  }

  /** Path part for operation `deletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete()` */
  static readonly DeletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDeletePath = '/preferred_athletes/{affiliate_id}/{crossfit_id}';

  /**
   * Delete Preferred Athlete Entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete$Response(params: DeletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Preferred Athlete Entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete(params: DeletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.deletePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch()` */
  static readonly UpdatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatchPath = '/preferred_athletes/{affiliate_id}/{crossfit_id}';

  /**
   * Update Preferred Athlete Entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch$Response(params: UpdatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiPreferredAthleteModel>> {
    return updatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Preferred Athlete Entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch(params: UpdatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch$Params, context?: HttpContext): Observable<apiPreferredAthleteModel> {
    return this.updatePreferredAthleteEntryPreferredAthletesAffiliateIdCrossfitIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiPreferredAthleteModel>): apiPreferredAthleteModel => r.body)
    );
  }

  /** Path part for operation `createPreferredAthleteEntryPreferredAthletesPost()` */
  static readonly CreatePreferredAthleteEntryPreferredAthletesPostPath = '/preferred_athletes/';

  /**
   * Create Preferred Athlete Entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPreferredAthleteEntryPreferredAthletesPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPreferredAthleteEntryPreferredAthletesPost$Response(params: CreatePreferredAthleteEntryPreferredAthletesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiPreferredAthleteModel>> {
    return createPreferredAthleteEntryPreferredAthletesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create Preferred Athlete Entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPreferredAthleteEntryPreferredAthletesPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPreferredAthleteEntryPreferredAthletesPost(params: CreatePreferredAthleteEntryPreferredAthletesPost$Params, context?: HttpContext): Observable<apiPreferredAthleteModel> {
    return this.createPreferredAthleteEntryPreferredAthletesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiPreferredAthleteModel>): apiPreferredAthleteModel => r.body)
    );
  }

  /** Path part for operation `initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost()` */
  static readonly InitializePreferredAthletesPreferredAthletesAffiliateIdInitializePostPath = '/preferred_athletes/{affiliate_id}/initialize';

  /**
   * Initialize Preferred Athletes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost$Response(params: InitializePreferredAthletesPreferredAthletesAffiliateIdInitializePost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiPreferredAthletesInitResponse>> {
    return initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Initialize Preferred Athletes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost(params: InitializePreferredAthletesPreferredAthletesAffiliateIdInitializePost$Params, context?: HttpContext): Observable<apiPreferredAthletesInitResponse> {
    return this.initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiPreferredAthletesInitResponse>): apiPreferredAthletesInitResponse => r.body)
    );
  }

}
