/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createNewHeatsSetupHeatsSetupPost } from '../fn/heats-setup/create-new-heats-setup-heats-setup-post';
import { CreateNewHeatsSetupHeatsSetupPost$Params } from '../fn/heats-setup/create-new-heats-setup-heats-setup-post';
import { deleteExistingHeatsSetupHeatsSetupHeatIdDelete } from '../fn/heats-setup/delete-existing-heats-setup-heats-setup-heat-id-delete';
import { DeleteExistingHeatsSetupHeatsSetupHeatIdDelete$Params } from '../fn/heats-setup/delete-existing-heats-setup-heats-setup-heat-id-delete';
import { getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet } from '../fn/heats-setup/get-heats-setup-by-affiliate-id-heats-setup-affiliate-affiliate-id-get';
import { GetHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet$Params } from '../fn/heats-setup/get-heats-setup-by-affiliate-id-heats-setup-affiliate-affiliate-id-get';
import { getHeatsSetupByIdHeatsSetupHeatIdGet } from '../fn/heats-setup/get-heats-setup-by-id-heats-setup-heat-id-get';
import { GetHeatsSetupByIdHeatsSetupHeatIdGet$Params } from '../fn/heats-setup/get-heats-setup-by-id-heats-setup-heat-id-get';
import { getHeatsSetupListHeatsSetupGet } from '../fn/heats-setup/get-heats-setup-list-heats-setup-get';
import { GetHeatsSetupListHeatsSetupGet$Params } from '../fn/heats-setup/get-heats-setup-list-heats-setup-get';
import { apiHeatsSetupModel } from '../models/api-heats-setup-model';
import { initializeHeatsSetupHeatsSetupInitializePost } from '../fn/heats-setup/initialize-heats-setup-heats-setup-initialize-post';
import { InitializeHeatsSetupHeatsSetupInitializePost$Params } from '../fn/heats-setup/initialize-heats-setup-heats-setup-initialize-post';
import { updateExistingHeatsSetupHeatsSetupHeatIdPatch } from '../fn/heats-setup/update-existing-heats-setup-heats-setup-heat-id-patch';
import { UpdateExistingHeatsSetupHeatsSetupHeatIdPatch$Params } from '../fn/heats-setup/update-existing-heats-setup-heats-setup-heat-id-patch';

@Injectable({ providedIn: 'root' })
export class apiHeatsSetupService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getHeatsSetupListHeatsSetupGet()` */
  static readonly GetHeatsSetupListHeatsSetupGetPath = '/heats_setup/';

  /**
   * Get Heats Setup List.
   *
   * Get all heats setup configurations.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHeatsSetupListHeatsSetupGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatsSetupListHeatsSetupGet$Response(params?: GetHeatsSetupListHeatsSetupGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatsSetupModel>>> {
    return getHeatsSetupListHeatsSetupGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Heats Setup List.
   *
   * Get all heats setup configurations.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHeatsSetupListHeatsSetupGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatsSetupListHeatsSetupGet(params?: GetHeatsSetupListHeatsSetupGet$Params, context?: HttpContext): Observable<Array<apiHeatsSetupModel>> {
    return this.getHeatsSetupListHeatsSetupGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiHeatsSetupModel>>): Array<apiHeatsSetupModel> => r.body)
    );
  }

  /** Path part for operation `createNewHeatsSetupHeatsSetupPost()` */
  static readonly CreateNewHeatsSetupHeatsSetupPostPath = '/heats_setup/';

  /**
   * Create New Heats Setup.
   *
   * Create a new heats setup configuration.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createNewHeatsSetupHeatsSetupPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewHeatsSetupHeatsSetupPost$Response(params: CreateNewHeatsSetupHeatsSetupPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsSetupModel>> {
    return createNewHeatsSetupHeatsSetupPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create New Heats Setup.
   *
   * Create a new heats setup configuration.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createNewHeatsSetupHeatsSetupPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNewHeatsSetupHeatsSetupPost(params: CreateNewHeatsSetupHeatsSetupPost$Params, context?: HttpContext): Observable<apiHeatsSetupModel> {
    return this.createNewHeatsSetupHeatsSetupPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatsSetupModel>): apiHeatsSetupModel => r.body)
    );
  }

  /** Path part for operation `initializeHeatsSetupHeatsSetupInitializePost()` */
  static readonly InitializeHeatsSetupHeatsSetupInitializePostPath = '/heats_setup/initialize';

  /**
   * Initialize Heats Setup.
   *
   * Initialize heats setup from constants with validation.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initializeHeatsSetupHeatsSetupInitializePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializeHeatsSetupHeatsSetupInitializePost$Response(params?: InitializeHeatsSetupHeatsSetupInitializePost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
    return initializeHeatsSetupHeatsSetupInitializePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Initialize Heats Setup.
   *
   * Initialize heats setup from constants with validation.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initializeHeatsSetupHeatsSetupInitializePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializeHeatsSetupHeatsSetupInitializePost(params?: InitializeHeatsSetupHeatsSetupInitializePost$Params, context?: HttpContext): Observable<any> {
    return this.initializeHeatsSetupHeatsSetupInitializePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<any>): any => r.body)
    );
  }

  /** Path part for operation `getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet()` */
  static readonly GetHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGetPath = '/heats_setup/affiliate/{affiliate_id}';

  /**
   * Get Heats Setup By Affiliate Id.
   *
   * Get all heats setup for a specific affiliate.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet$Response(params: GetHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatsSetupModel>>> {
    return getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Heats Setup By Affiliate Id.
   *
   * Get all heats setup for a specific affiliate.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet(params: GetHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet$Params, context?: HttpContext): Observable<Array<apiHeatsSetupModel>> {
    return this.getHeatsSetupByAffiliateIdHeatsSetupAffiliateAffiliateIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiHeatsSetupModel>>): Array<apiHeatsSetupModel> => r.body)
    );
  }

  /** Path part for operation `getHeatsSetupByIdHeatsSetupHeatIdGet()` */
  static readonly GetHeatsSetupByIdHeatsSetupHeatIdGetPath = '/heats_setup/{heat_id}';

  /**
   * Get Heats Setup By Id.
   *
   * Get a specific heats setup by ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHeatsSetupByIdHeatsSetupHeatIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatsSetupByIdHeatsSetupHeatIdGet$Response(params: GetHeatsSetupByIdHeatsSetupHeatIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsSetupModel>> {
    return getHeatsSetupByIdHeatsSetupHeatIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Heats Setup By Id.
   *
   * Get a specific heats setup by ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHeatsSetupByIdHeatsSetupHeatIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHeatsSetupByIdHeatsSetupHeatIdGet(params: GetHeatsSetupByIdHeatsSetupHeatIdGet$Params, context?: HttpContext): Observable<apiHeatsSetupModel> {
    return this.getHeatsSetupByIdHeatsSetupHeatIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatsSetupModel>): apiHeatsSetupModel => r.body)
    );
  }

  /** Path part for operation `deleteExistingHeatsSetupHeatsSetupHeatIdDelete()` */
  static readonly DeleteExistingHeatsSetupHeatsSetupHeatIdDeletePath = '/heats_setup/{heat_id}';

  /**
   * Delete Existing Heats Setup.
   *
   * Delete a heats setup configuration.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteExistingHeatsSetupHeatsSetupHeatIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExistingHeatsSetupHeatsSetupHeatIdDelete$Response(params: DeleteExistingHeatsSetupHeatsSetupHeatIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteExistingHeatsSetupHeatsSetupHeatIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete Existing Heats Setup.
   *
   * Delete a heats setup configuration.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteExistingHeatsSetupHeatsSetupHeatIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteExistingHeatsSetupHeatsSetupHeatIdDelete(params: DeleteExistingHeatsSetupHeatsSetupHeatIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.deleteExistingHeatsSetupHeatsSetupHeatIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateExistingHeatsSetupHeatsSetupHeatIdPatch()` */
  static readonly UpdateExistingHeatsSetupHeatsSetupHeatIdPatchPath = '/heats_setup/{heat_id}';

  /**
   * Update Existing Heats Setup.
   *
   * Update an existing heats setup configuration.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateExistingHeatsSetupHeatsSetupHeatIdPatch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExistingHeatsSetupHeatsSetupHeatIdPatch$Response(params: UpdateExistingHeatsSetupHeatsSetupHeatIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsSetupModel>> {
    return updateExistingHeatsSetupHeatsSetupHeatIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Existing Heats Setup.
   *
   * Update an existing heats setup configuration.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateExistingHeatsSetupHeatsSetupHeatIdPatch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateExistingHeatsSetupHeatsSetupHeatIdPatch(params: UpdateExistingHeatsSetupHeatsSetupHeatIdPatch$Params, context?: HttpContext): Observable<apiHeatsSetupModel> {
    return this.updateExistingHeatsSetupHeatsSetupHeatIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiHeatsSetupModel>): apiHeatsSetupModel => r.body)
    );
  }

}
