/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAffiliateConfigModel } from '../models/api-affiliate-config-model';
import { getAffiliateConfigAffiliateConfigAffiliateIdYearGet } from '../fn/affiliate-config/get-affiliate-config-affiliate-config-affiliate-id-year-get';
import { GetAffiliateConfigAffiliateConfigAffiliateIdYearGet$Params } from '../fn/affiliate-config/get-affiliate-config-affiliate-config-affiliate-id-year-get';
import { initializeAffiliateConfigAffiliateConfigInitializePost } from '../fn/affiliate-config/initialize-affiliate-config-affiliate-config-initialize-post';
import { InitializeAffiliateConfigAffiliateConfigInitializePost$Params } from '../fn/affiliate-config/initialize-affiliate-config-affiliate-config-initialize-post';

@Injectable({ providedIn: 'root' })
export class apiAffiliateConfigService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAffiliateConfigAffiliateConfigAffiliateIdYearGet()` */
  static readonly GetAffiliateConfigAffiliateConfigAffiliateIdYearGetPath = '/affiliate_config/{affiliate_id}/{year}/';

  /**
   * Get Affiliate Config.
   *
   * Get affiliate config for a specific affiliate and year.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAffiliateConfigAffiliateConfigAffiliateIdYearGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAffiliateConfigAffiliateConfigAffiliateIdYearGet$Response(params: GetAffiliateConfigAffiliateConfigAffiliateIdYearGet$Params, context?: HttpContext): Observable<StrictHttpResponse<(apiAffiliateConfigModel | null)>> {
    return getAffiliateConfigAffiliateConfigAffiliateIdYearGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Affiliate Config.
   *
   * Get affiliate config for a specific affiliate and year.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAffiliateConfigAffiliateConfigAffiliateIdYearGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAffiliateConfigAffiliateConfigAffiliateIdYearGet(params: GetAffiliateConfigAffiliateConfigAffiliateIdYearGet$Params, context?: HttpContext): Observable<(apiAffiliateConfigModel | null)> {
    return this.getAffiliateConfigAffiliateConfigAffiliateIdYearGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<(apiAffiliateConfigModel | null)>): (apiAffiliateConfigModel | null) => r.body)
    );
  }

  /** Path part for operation `initializeAffiliateConfigAffiliateConfigInitializePost()` */
  static readonly InitializeAffiliateConfigAffiliateConfigInitializePostPath = '/affiliate_config/initialize';

  /**
   * Initialize Affiliate Config.
   *
   * Initialize affiliate configs with default values from constants.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initializeAffiliateConfigAffiliateConfigInitializePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializeAffiliateConfigAffiliateConfigInitializePost$Response(params?: InitializeAffiliateConfigAffiliateConfigInitializePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAffiliateConfigModel>>> {
    return initializeAffiliateConfigAffiliateConfigInitializePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Initialize Affiliate Config.
   *
   * Initialize affiliate configs with default values from constants.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initializeAffiliateConfigAffiliateConfigInitializePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initializeAffiliateConfigAffiliateConfigInitializePost(params?: InitializeAffiliateConfigAffiliateConfigInitializePost$Params, context?: HttpContext): Observable<Array<apiAffiliateConfigModel>> {
    return this.initializeAffiliateConfigAffiliateConfigInitializePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiAffiliateConfigModel>>): Array<apiAffiliateConfigModel> => r.body)
    );
  }

}
