/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAppreciationModelOutput } from '../models/api-appreciation-model-output';
import { getAppreciationAppreciationAffiliateIdYearOrdinalGet } from '../fn/appreciation/get-appreciation-appreciation-affiliate-id-year-ordinal-get';
import { GetAppreciationAppreciationAffiliateIdYearOrdinalGet$Params } from '../fn/appreciation/get-appreciation-appreciation-affiliate-id-year-ordinal-get';
import { updateAppreciationAppreciationAthleteIdOrdinalPost } from '../fn/appreciation/update-appreciation-appreciation-athlete-id-ordinal-post';
import { UpdateAppreciationAppreciationAthleteIdOrdinalPost$Params } from '../fn/appreciation/update-appreciation-appreciation-athlete-id-ordinal-post';

@Injectable({ providedIn: 'root' })
export class apiAppreciationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAppreciationAppreciationAffiliateIdYearOrdinalGet()` */
  static readonly GetAppreciationAppreciationAffiliateIdYearOrdinalGetPath = '/appreciation/{affiliate_id}/{year}/{ordinal}';

  /**
   * Get Appreciation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAppreciationAppreciationAffiliateIdYearOrdinalGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAppreciationAppreciationAffiliateIdYearOrdinalGet$Response(params: GetAppreciationAppreciationAffiliateIdYearOrdinalGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAppreciationModelOutput>>> {
    return getAppreciationAppreciationAffiliateIdYearOrdinalGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Appreciation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAppreciationAppreciationAffiliateIdYearOrdinalGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAppreciationAppreciationAffiliateIdYearOrdinalGet(params: GetAppreciationAppreciationAffiliateIdYearOrdinalGet$Params, context?: HttpContext): Observable<Array<apiAppreciationModelOutput>> {
    return this.getAppreciationAppreciationAffiliateIdYearOrdinalGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<apiAppreciationModelOutput>>): Array<apiAppreciationModelOutput> => r.body)
    );
  }

  /** Path part for operation `updateAppreciationAppreciationAthleteIdOrdinalPost()` */
  static readonly UpdateAppreciationAppreciationAthleteIdOrdinalPostPath = '/appreciation/{athlete_id}/{ordinal}';

  /**
   * Update Appreciation.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateAppreciationAppreciationAthleteIdOrdinalPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAppreciationAppreciationAthleteIdOrdinalPost$Response(params: UpdateAppreciationAppreciationAthleteIdOrdinalPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAppreciationModelOutput>> {
    return updateAppreciationAppreciationAthleteIdOrdinalPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Update Appreciation.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateAppreciationAppreciationAthleteIdOrdinalPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateAppreciationAppreciationAthleteIdOrdinalPost(params: UpdateAppreciationAppreciationAthleteIdOrdinalPost$Params, context?: HttpContext): Observable<apiAppreciationModelOutput> {
    return this.updateAppreciationAppreciationAthleteIdOrdinalPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<apiAppreciationModelOutput>): apiAppreciationModelOutput => r.body)
    );
  }

}
