/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiPreferredAthleteCreate } from '../../models/api-preferred-athlete-create';
import { apiPreferredAthleteModel } from '../../models/api-preferred-athlete-model';

export interface CreatePreferredAthleteEntryPreferredAthletesPost$Params {
      body: apiPreferredAthleteCreate
}

export function createPreferredAthleteEntryPreferredAthletesPost(http: HttpClient, rootUrl: string, params: CreatePreferredAthleteEntryPreferredAthletesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiPreferredAthleteModel>> {
  const rb = new RequestBuilder(rootUrl, createPreferredAthleteEntryPreferredAthletesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiPreferredAthleteModel>;
    })
  );
}

createPreferredAthleteEntryPreferredAthletesPost.PATH = '/preferred_athletes/';
