/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeletePreferredAthleteEntryPreferredAthletesCrossfitIdDelete$Params {
  crossfit_id: number;
}

export function deletePreferredAthleteEntryPreferredAthletesCrossfitIdDelete(http: HttpClient, rootUrl: string, params: DeletePreferredAthleteEntryPreferredAthletesCrossfitIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deletePreferredAthleteEntryPreferredAthletesCrossfitIdDelete.PATH, 'delete');
  if (params) {
    rb.path('crossfit_id', params.crossfit_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deletePreferredAthleteEntryPreferredAthletesCrossfitIdDelete.PATH = '/preferred_athletes/{crossfit_id}';
