/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiPreferredAthletesInitResponse } from '../../models/api-preferred-athletes-init-response';

export interface InitializePreferredAthletesPreferredAthletesAffiliateIdInitializePost$Params {
  affiliate_id: number;
}

export function initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost(http: HttpClient, rootUrl: string, params: InitializePreferredAthletesPreferredAthletesAffiliateIdInitializePost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiPreferredAthletesInitResponse>> {
  const rb = new RequestBuilder(rootUrl, initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost.PATH, 'post');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiPreferredAthletesInitResponse>;
    })
  );
}

initializePreferredAthletesPreferredAthletesAffiliateIdInitializePost.PATH = '/preferred_athletes/{affiliate_id}/initialize';
