/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiPreferredAthleteModel } from '../../models/api-preferred-athlete-model';
import { apiPreferredAthleteUpdate } from '../../models/api-preferred-athlete-update';

export interface UpdatePreferredAthleteEntryPreferredAthletesCrossfitIdPatch$Params {
  crossfit_id: number;
      body: apiPreferredAthleteUpdate
}

export function updatePreferredAthleteEntryPreferredAthletesCrossfitIdPatch(http: HttpClient, rootUrl: string, params: UpdatePreferredAthleteEntryPreferredAthletesCrossfitIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiPreferredAthleteModel>> {
  const rb = new RequestBuilder(rootUrl, updatePreferredAthleteEntryPreferredAthletesCrossfitIdPatch.PATH, 'patch');
  if (params) {
    rb.path('crossfit_id', params.crossfit_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiPreferredAthleteModel>;
    })
  );
}

updatePreferredAthleteEntryPreferredAthletesCrossfitIdPatch.PATH = '/preferred_athletes/{crossfit_id}';
