/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AssignAthleteToTeamAthleteTeamAssignPut$Params {
  crossfit_id: number;
  year: number;
  team_name: string;
  team_role: number;
}

export function assignAthleteToTeamAthleteTeamAssignPut(http: HttpClient, rootUrl: string, params: AssignAthleteToTeamAthleteTeamAssignPut$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, assignAthleteToTeamAthleteTeamAssignPut.PATH, 'put');
  if (params) {
    rb.query('crossfit_id', params.crossfit_id, {});
    rb.query('year', params.year, {});
    rb.query('team_name', params.team_name, {});
    rb.query('team_role', params.team_role, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

assignAthleteToTeamAthleteTeamAssignPut.PATH = '/athlete/team/assign';
