/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiTeamName } from '../../models/api-team-name';

export interface GetTeamNamesAthleteTeamNamesGet$Params {
  affiliate_id: number;
  year: number;
}

export function getTeamNamesAthleteTeamNamesGet(http: HttpClient, rootUrl: string, params: GetTeamNamesAthleteTeamNamesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiTeamName>>> {
  const rb = new RequestBuilder(rootUrl, getTeamNamesAthleteTeamNamesGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiTeamName>>;
    })
  );
}

getTeamNamesAthleteTeamNamesGet.PATH = '/athlete/team_names';
