/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAthleteDetail } from '../../models/api-athlete-detail';

export interface GetMyAthleteDataAthleteMeGet$Params {
}

export function getMyAthleteDataAthleteMeGet(http: HttpClient, rootUrl: string, params?: GetMyAthleteDataAthleteMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAthleteDetail>> {
  const rb = new RequestBuilder(rootUrl, getMyAthleteDataAthleteMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiAthleteDetail>;
    })
  );
}

getMyAthleteDataAthleteMeGet.PATH = '/athlete/me';
