/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAthleteDetail } from '../../models/api-athlete-detail';

export interface GetAthleteDetailAllAthleteDetailAllGet$Params {
  affiliate_id: number;
  team_name?: (string | null);
  age_category?: ('U18' | 'Open' | 'Masters' | 'Masters 55+' | null);
  gender?: ('F' | 'M' | null);
}

export function getAthleteDetailAllAthleteDetailAllGet(http: HttpClient, rootUrl: string, params: GetAthleteDetailAllAthleteDetailAllGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAthleteDetail>>> {
  const rb = new RequestBuilder(rootUrl, getAthleteDetailAllAthleteDetailAllGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('team_name', params.team_name, {});
    rb.query('age_category', params.age_category, {});
    rb.query('gender', params.gender, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAthleteDetail>>;
    })
  );
}

getAthleteDetailAllAthleteDetailAllGet.PATH = '/athlete/detail/all';
