/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAffiliateAthlete } from '../../models/api-affiliate-athlete';

export interface GetAthleteListAthleteListGet$Params {
  affiliate_id?: (number | null);
  year?: (number | null);
}

export function getAthleteListAthleteListGet(http: HttpClient, rootUrl: string, params?: GetAthleteListAthleteListGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAffiliateAthlete>>> {
  const rb = new RequestBuilder(rootUrl, getAthleteListAthleteListGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAffiliateAthlete>>;
    })
  );
}

getAthleteListAthleteListGet.PATH = '/athlete/list';
