/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAutoTeamAssignment } from '../../models/api-auto-team-assignment';

export interface RandomAssignAthletesAthleteTeamRandomAssignGet$Params {
  affiliate_id: number;
  year: number;
  assign_from_team_name: string;
      body: Array<string>
}

export function randomAssignAthletesAthleteTeamRandomAssignGet(http: HttpClient, rootUrl: string, params: RandomAssignAthletesAthleteTeamRandomAssignGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAutoTeamAssignment>>> {
  const rb = new RequestBuilder(rootUrl, randomAssignAthletesAthleteTeamRandomAssignGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
    rb.query('assign_from_team_name', params.assign_from_team_name, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAutoTeamAssignment>>;
    })
  );
}

randomAssignAthletesAthleteTeamRandomAssignGet.PATH = '/athlete/team/random_assign';
