/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiCreateHomeBlogModel } from '../../models/api-create-home-blog-model';

export interface AddHomeBlogHomeBlogPost$Params {
  affiliate_id: number;
  year: number;
      body: apiCreateHomeBlogModel
}

export function addHomeBlogHomeBlogPost(http: HttpClient, rootUrl: string, params: AddHomeBlogHomeBlogPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, addHomeBlogHomeBlogPost.PATH, 'post');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

addHomeBlogHomeBlogPost.PATH = '/home_blog/';
