/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiCreateHomeBlogModel } from '../../models/api-create-home-blog-model';

export interface UpdateHomeBlogHomeBlogPatch$Params {
  '_id': string;
      body: apiCreateHomeBlogModel
}

export function updateHomeBlogHomeBlogPatch(http: HttpClient, rootUrl: string, params: UpdateHomeBlogHomeBlogPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateHomeBlogHomeBlogPatch.PATH, 'patch');
  if (params) {
    rb.query('_id', params['_id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateHomeBlogHomeBlogPatch.PATH = '/home_blog/';
