/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAthleteNotSignedUp } from '../../models/api-athlete-not-signed-up';

export interface GetAthletesNotSignedUpFireauthAthletesNotSignedUpGet$Params {
  affiliate_id: number;
  year: number;
}

export function getAthletesNotSignedUpFireauthAthletesNotSignedUpGet(http: HttpClient, rootUrl: string, params: GetAthletesNotSignedUpFireauthAthletesNotSignedUpGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiAthleteNotSignedUp>>> {
  const rb = new RequestBuilder(rootUrl, getAthletesNotSignedUpFireauthAthletesNotSignedUpGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiAthleteNotSignedUp>>;
    })
  );
}

getAthletesNotSignedUpFireauthAthletesNotSignedUpGet.PATH = '/fireauth/athletes-not-signed-up';
