/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiEventsModel } from '../../models/api-events-model';

export interface GetEventsWithDataCfeventsGet$Params {
  affiliate_id: number;
}

export function getEventsWithDataCfeventsGet(http: HttpClient, rootUrl: string, params: GetEventsWithDataCfeventsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiEventsModel>>> {
  const rb = new RequestBuilder(rootUrl, getEventsWithDataCfeventsGet.PATH, 'get');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiEventsModel>>;
    })
  );
}

getEventsWithDataCfeventsGet.PATH = '/cfevents/';
