/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiEventsModel } from '../../models/api-events-model';
import { apiEventsUpdate } from '../../models/api-events-update';

export interface UpdateCfeventCfeventsYearOrdinalPatch$Params {
  year: number;
  ordinal: number;
      body: apiEventsUpdate
}

export function updateCfeventCfeventsYearOrdinalPatch(http: HttpClient, rootUrl: string, params: UpdateCfeventCfeventsYearOrdinalPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiEventsModel>> {
  const rb = new RequestBuilder(rootUrl, updateCfeventCfeventsYearOrdinalPatch.PATH, 'patch');
  if (params) {
    rb.path('year', params.year, {});
    rb.path('ordinal', params.ordinal, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiEventsModel>;
    })
  );
}

updateCfeventCfeventsYearOrdinalPatch.PATH = '/cfevents/{year}/{ordinal}/';
