JUDGE_TIMESLOTS = [
    "Fri 7AM",
    "Fri 8AM",
    "Fri 5PM",
    "Fri 6PM",
    "Fri 7PM",
    "Sat 6AM",
    "Sat 7AM",
    "Sat 8AM",
    "Sat 9AM",
    "Sat 5PM",
    "Sat 6PM",
    "Sat 7PM",
    "Sun 6AM",
    "Sun 7AM",
    "Sun 8AM",
    "Sun 9AM",
    "Mon 7AM",
    "Mon 8AM",
    "Mon 5PM",
    "Mon 6PM",
]
