/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgeAvailabilityCreate } from '../../models/api-judge-availability-create';
import { apiJudgeAvailabilityModel } from '../../models/api-judge-availability-model';

export interface CreateNewJudgeAvailabilityJudgeAvailabilityPost$Params {
      body: apiJudgeAvailabilityCreate
}

export function createNewJudgeAvailabilityJudgeAvailabilityPost(http: HttpClient, rootUrl: string, params: CreateNewJudgeAvailabilityJudgeAvailabilityPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgeAvailabilityModel>> {
  const rb = new RequestBuilder(rootUrl, createNewJudgeAvailabilityJudgeAvailabilityPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiJudgeAvailabilityModel>;
    })
  );
}

createNewJudgeAvailabilityJudgeAvailabilityPost.PATH = '/judge-availability/';
