/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgeAvailabilityModel } from '../../models/api-judge-availability-model';

export interface GetMyJudgeAvailabilityJudgeAvailabilityMeGet$Params {
}

export function getMyJudgeAvailabilityJudgeAvailabilityMeGet(http: HttpClient, rootUrl: string, params?: GetMyJudgeAvailabilityJudgeAvailabilityMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiJudgeAvailabilityModel>>> {
  const rb = new RequestBuilder(rootUrl, getMyJudgeAvailabilityJudgeAvailabilityMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiJudgeAvailabilityModel>>;
    })
  );
}

getMyJudgeAvailabilityJudgeAvailabilityMeGet.PATH = '/judge-availability/me';
