/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiJudgeAvailabilityModel } from '../../models/api-judge-availability-model';

export interface GetJudgeAvailabilityByIdJudgeAvailabilityAvailabilityIdGet$Params {
  availability_id: string;
}

export function getJudgeAvailabilityByIdJudgeAvailabilityAvailabilityIdGet(http: HttpClient, rootUrl: string, params: GetJudgeAvailabilityByIdJudgeAvailabilityAvailabilityIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<apiJudgeAvailabilityModel>> {
  const rb = new RequestBuilder(rootUrl, getJudgeAvailabilityByIdJudgeAvailabilityAvailabilityIdGet.PATH, 'get');
  if (params) {
    rb.path('availability_id', params.availability_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiJudgeAvailabilityModel>;
    })
  );
}

getJudgeAvailabilityByIdJudgeAvailabilityAvailabilityIdGet.PATH = '/judge-availability/{availability_id}';
