/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UpdateAttendanceAttendanceAffiliateIdYearPost$Params {
  affiliate_id: number;
  year: number;
  competitor_id: number;
  ordinal: number;
}

export function updateAttendanceAttendanceAffiliateIdYearPost(http: HttpClient, rootUrl: string, params: UpdateAttendanceAttendanceAffiliateIdYearPost$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, updateAttendanceAttendanceAffiliateIdYearPost.PATH, 'post');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.query('competitor_id', params.competitor_id, {});
    rb.query('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

updateAttendanceAttendanceAffiliateIdYearPost.PATH = '/attendance/{affiliate_id}/{year}/';
