/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAffiliateConfigModel } from '../../models/api-affiliate-config-model';

export interface GetAffiliateConfigAffiliateConfigAffiliateIdYearGet$Params {
  affiliate_id: number;
  year: number;
}

export function getAffiliateConfigAffiliateConfigAffiliateIdYearGet(http: HttpClient, rootUrl: string, params: GetAffiliateConfigAffiliateConfigAffiliateIdYearGet$Params, context?: HttpContext): Observable<StrictHttpResponse<(apiAffiliateConfigModel | null)>> {
  const rb = new RequestBuilder(rootUrl, getAffiliateConfigAffiliateConfigAffiliateIdYearGet.PATH, 'get');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(apiAffiliateConfigModel | null)>;
    })
  );
}

getAffiliateConfigAffiliateConfigAffiliateIdYearGet.PATH = '/affiliate_config/{affiliate_id}/{year}/';
