/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiAffiliateConfigModel } from '../../models/api-affiliate-config-model';

export interface InitializeAffiliateConfigAffiliateConfigInitializePost$Params {
  affiliate_id: number;
  year: number;
}

export function initializeAffiliateConfigAffiliateConfigInitializePost(http: HttpClient, rootUrl: string, params: InitializeAffiliateConfigAffiliateConfigInitializePost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiAffiliateConfigModel>> {
  const rb = new RequestBuilder(rootUrl, initializeAffiliateConfigAffiliateConfigInitializePost.PATH, 'post');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiAffiliateConfigModel>;
    })
  );
}

initializeAffiliateConfigAffiliateConfigInitializePost.PATH = '/affiliate_config/initialize';
