/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiSideScoreModel } from '../../models/api-side-score-model';

export interface GetSidescoresSidescoreAffiliateIdYearGet$Params {
  affiliate_id: number;
  year: number;
}

export function getSidescoresSidescoreAffiliateIdYearGet(http: HttpClient, rootUrl: string, params: GetSidescoresSidescoreAffiliateIdYearGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiSideScoreModel>>> {
  const rb = new RequestBuilder(rootUrl, getSidescoresSidescoreAffiliateIdYearGet.PATH, 'get');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiSideScoreModel>>;
    })
  );
}

getSidescoresSidescoreAffiliateIdYearGet.PATH = '/sidescore/{affiliate_id}/{year}/';
