/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiSideScoreModel } from '../../models/api-side-score-model';

export interface UpdateSidescoresSidescoreAffiliateIdYearPost$Params {
  affiliate_id: number;
  year: number;
  ordinal: number;
  score_type: 'side_challenge' | 'spirit' | 'social_media';
  team_name: string;
  score: number;
}

export function updateSidescoresSidescoreAffiliateIdYearPost(http: HttpClient, rootUrl: string, params: UpdateSidescoresSidescoreAffiliateIdYearPost$Params, context?: HttpContext): Observable<StrictHttpResponse<apiSideScoreModel>> {
  const rb = new RequestBuilder(rootUrl, updateSidescoresSidescoreAffiliateIdYearPost.PATH, 'post');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.query('ordinal', params.ordinal, {});
    rb.query('score_type', params.score_type, {});
    rb.query('team_name', params.team_name, {});
    rb.query('score', params.score, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiSideScoreModel>;
    })
  );
}

updateSidescoresSidescoreAffiliateIdYearPost.PATH = '/sidescore/{affiliate_id}/{year}/';
