/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiUserScoreModel } from '../../models/api-user-score-model';

export interface GetMyScoresScoreMeGet$Params {
}

export function getMyScoresScoreMeGet(http: HttpClient, rootUrl: string, params?: GetMyScoresScoreMeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiUserScoreModel>>> {
  const rb = new RequestBuilder(rootUrl, getMyScoresScoreMeGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiUserScoreModel>>;
    })
  );
}

getMyScoresScoreMeGet.PATH = '/score/me';
