/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiScoreModel } from '../../models/api-score-model';

export interface GetScoresScoreAffiliateIdYearGet$Params {
  affiliate_id: number;
  year: number;
  ordinal?: (number | null);
  gender?: ('F' | 'M' | null);
  age_category?: ('Open' | 'Masters' | 'Masters 55+' | null);
  affiliate_scaled?: ('RX' | 'Scaled' | null);
  top_n?: (number | null);
}

export function getScoresScoreAffiliateIdYearGet(http: HttpClient, rootUrl: string, params: GetScoresScoreAffiliateIdYearGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiScoreModel>>> {
  const rb = new RequestBuilder(rootUrl, getScoresScoreAffiliateIdYearGet.PATH, 'get');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.query('ordinal', params.ordinal, {});
    rb.query('gender', params.gender, {});
    rb.query('age_category', params.age_category, {});
    rb.query('affiliate_scaled', params.affiliate_scaled, {});
    rb.query('top_n', params.top_n, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiScoreModel>>;
    })
  );
}

getScoresScoreAffiliateIdYearGet.PATH = '/score/{affiliate_id}/{year}';
