/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiTeamScoreModel } from '../../models/api-team-score-model';

export interface GetTeamScoresOrdinalScoreTeamAffiliateIdYearOrdinalGet$Params {
  affiliate_id: number;
  year: number;
  ordinal: number;
}

export function getTeamScoresOrdinalScoreTeamAffiliateIdYearOrdinalGet(http: HttpClient, rootUrl: string, params: GetTeamScoresOrdinalScoreTeamAffiliateIdYearOrdinalGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiTeamScoreModel>>> {
  const rb = new RequestBuilder(rootUrl, getTeamScoresOrdinalScoreTeamAffiliateIdYearOrdinalGet.PATH, 'get');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.path('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiTeamScoreModel>>;
    })
  );
}

getTeamScoresOrdinalScoreTeamAffiliateIdYearOrdinalGet.PATH = '/score/team/{affiliate_id}/{year}/{ordinal}';
