/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteIndividualSideScoresIndividualSideScoreDelete$Params {
  affiliate_id: number;
  year: number;
  crossfit_id: number;
  ordinal: number;
}

export function deleteIndividualSideScoresIndividualSideScoreDelete(http: HttpClient, rootUrl: string, params: DeleteIndividualSideScoresIndividualSideScoreDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteIndividualSideScoresIndividualSideScoreDelete.PATH, 'delete');
  if (params) {
    rb.query('affiliate_id', params.affiliate_id, {});
    rb.query('year', params.year, {});
    rb.query('crossfit_id', params.crossfit_id, {});
    rb.query('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteIndividualSideScoresIndividualSideScoreDelete.PATH = '/individual_side_score/';
