/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete$Params {
  start_time: string;
  affiliate_id: number;
  year: number;
  ordinal: number;
}

export function deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete(http: HttpClient, rootUrl: string, params: DeleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete.PATH, 'delete');
  if (params) {
    rb.path('start_time', params.start_time, {});
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.path('ordinal', params.ordinal, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteExistingHeatHeatsYearAffiliateIdOrdinalStartTimeDelete.PATH = '/heats/{year}/{affiliate_id}/{ordinal}/{start_time}';
