/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatsModel } from '../../models/api-heats-model';

export interface GetHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet$Params {
  affiliate_id: number;
  year: number;
  ordinal: number;
  is_locked?: (boolean | null);
  is_published?: (boolean | null);
}

export function getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet(http: HttpClient, rootUrl: string, params: GetHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<apiHeatsModel>>> {
  const rb = new RequestBuilder(rootUrl, getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet.PATH, 'get');
  if (params) {
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.path('ordinal', params.ordinal, {});
    rb.query('is_locked', params.is_locked, {});
    rb.query('is_published', params.is_published, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<apiHeatsModel>>;
    })
  );
}

getHeatsByFilterHeatsFilterYearAffiliateIdOrdinalGet.PATH = '/heats/filter/{year}/{affiliate_id}/{ordinal}';
