/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { apiHeatsModel } from '../../models/api-heats-model';
import { apiHeatsUpdate } from '../../models/api-heats-update';

export interface UpdateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch$Params {
  start_time: string;
  affiliate_id: number;
  year: number;
  ordinal: number;
      body: apiHeatsUpdate
}

export function updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch(http: HttpClient, rootUrl: string, params: UpdateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<apiHeatsModel>> {
  const rb = new RequestBuilder(rootUrl, updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch.PATH, 'patch');
  if (params) {
    rb.path('start_time', params.start_time, {});
    rb.path('affiliate_id', params.affiliate_id, {});
    rb.path('year', params.year, {});
    rb.path('ordinal', params.ordinal, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<apiHeatsModel>;
    })
  );
}

updateExistingHeatHeatsYearAffiliateIdOrdinalStartTimePatch.PATH = '/heats/{year}/{affiliate_id}/{ordinal}/{start_time}';
